#!/usr/bin/env python3

from load_into_database import CollisionRow
import pytest

# A list of tuples, with each tuple containing a row ready to be parsed, and
# the answer that should be returned from doing so. The tuple is of the form
# (row, answer)
ROWS = (
    (
        #Case_ID                 Collision_Year  Process_Date  Jurisdiction  Collision_Date  Collision_Time  Officer_ID  Reporting_District  DOW    CHP_Shift  Population  County_City_Location  Special_Condition  Beat_Type  CHP_Beat_Type  City_Division_LAPD  CHP_Beat_Class  Beat_Number  Primary_Road                       Secondary_Road   Distance      Direction  Intersection  Weather_1  Weather_2  State_Highway_Indicator  Caltrans_County  Caltrans_District  State_Route  Route_Suffix  Postmile_Prefix  Postmile       Location_Type  Ramp_Intersection  Side_Of_Highway  Tow_Away  Collision_Severity  Killed_Victims  Injured_Victims  Party_Count  Primary_Collision_Factor  PCF_Violation_Code  PCF_Violation_Category  PCF_Violation  PCF_Violation_Subsection  Hit_And_Run  Type_Of_Collision  Motor_Vehicle_Involved_With  Ped_Action  Road_Surface  Road_Condition_1  Road_Condition_2  Lighting  Control_Device  CHP_Road_Type  Pedestrian_Collision  Bicycle_Collision  Motorcycle_Collision  Truck_Collision  Not_Private_Property  Alcohol_Involved  Statewide_Vehicle_Type_At_Fault  CHP_Vehicle_Type_At_Fault  Severe_Injury_Count  Other_Visible_Injury_Count  Complaint_Of_Pain_Injury_Count  Pedestrian_Killed_Count  Pedestrian_Injured_Count  Bicyclist_Killed_Count  Bicyclist_Injured_Count  Motorcyclist_Killed_Count  Motorcyclist_Injured_Count  Primary_Ramp  Secondary_Ramp  Latitude    Longitude
        ['0100010101011401155',  '2001',         '20010416',   '0000',       '20010101',     '114',          '1155qq',   '0',                '1',   '4',       '4',        '198',                '-',               '0',       'A',           '',                 '0',            '073',       'DUBLIN_BL',                       'SCARLETT_CT',   '267000000',  'W',       'N',          'A',       'D',       'N',                     'abc',           '20',              '280',       'A',          'A',             '234000.222',  'H',           '8',               'N',             'Y',      '0',                '999',          '999',           '999',       'A',                      'C',                '01',                   '23152',       'A',                      'F',         'E',               'I',                         'A',        'A',          'H',              'C',              'C',      'D',            'A',           'N',                  'N',               'N',                  'N',             'NY',                 'N',              'A',                             '00',                      '0',                 '0',                        '0',                            '0',                     '0',                      '0',                    '0',                     '0',                       '0',                        'NF-NB',      'EF-EB',        '37.7749',  '122.4194'],
        ['0100010101011401155',                                0,                                            '1155qq',   '0',                       '4',       '4',        '198',                None,              '0',       'A',           None,               '0',            '073',       'DUBLIN_BL',                       'SCARLETT_CT',   267000000.,   'W',       False,        'A',       'D',       False,                   'abc',           20,                280,         'A',          'A',             234000.222,    'H',           8,                 'N',             True,     0,                  999,            999,             999,         'A',                      'C',                '01',                   23152,         'A',                      'F',         'E',               'I',                         'A',        'A',          'H',              'C',              'C',      'D',            'A',           False,                False,             False,                False,           False,                False,            'A',                             '00',                      0,                   0,                          0,                              0,                       0,                        0,                      0,                       0,                         0,                          'NF-NB',      'EF-EB',        37.7749,    -122.4194, "2001-01-01", "01:14:00", "2001-04-16"],
    ),
    (
        #Case_ID                 Collision_Year  Process_Date  Jurisdiction  Collision_Date  Collision_Time  Officer_ID  Reporting_District  DOW    CHP_Shift  Population  County_City_Location  Special_Condition  Beat_Type  CHP_Beat_Type  City_Division_LAPD  CHP_Beat_Class  Beat_Number  Primary_Road                       Secondary_Road   Distance      Direction  Intersection  Weather_1  Weather_2  State_Highway_Indicator  Caltrans_County  Caltrans_District  State_Route  Route_Suffix  Postmile_Prefix  Postmile       Location_Type  Ramp_Intersection  Side_Of_Highway  Tow_Away  Collision_Severity  Killed_Victims  Injured_Victims  Party_Count  Primary_Collision_Factor  PCF_Violation_Code  PCF_Violation_Category  PCF_Violation  PCF_Violation_Subsection  Hit_And_Run  Type_Of_Collision  Motor_Vehicle_Involved_With  Ped_Action  Road_Surface  Road_Condition_1  Road_Condition_2  Lighting  Control_Device  CHP_Road_Type  Pedestrian_Collision  Bicycle_Collision  Motorcycle_Collision  Truck_Collision  Not_Private_Property  Alcohol_Involved  Statewide_Vehicle_Type_At_Fault  CHP_Vehicle_Type_At_Fault  Severe_Injury_Count  Other_Visible_Injury_Count  Complaint_Of_Pain_Injury_Count  Pedestrian_Killed_Count  Pedestrian_Injured_Count  Bicyclist_Killed_Count  Bicyclist_Injured_Count  Motorcyclist_Killed_Count  Motorcyclist_Injured_Count  Primary_Ramp  Secondary_Ramp  Latitude    Longitude
        ['3337743',              '2007',         '20080214',   '1900',       '20070821',     '0910',         '478242',   '0453',             '2',   '5',       '0',        '1949',               '0',               '8',       '0',           '-',                '-',            '43T1',      'HOXIE_AV',                        'IMPERIAL_HWY',  '400.02',     'S',       'Y',          'A',       '-',       'Y',                     '123',           '99',              '80',        'B',          'B',             '38',          'I',           '4',               'E',             'N',      '4',                '0',            '0',             '1',         'E',                      'W',                '08',                   '22107',       '',                       'N',         'E',               'J',                         'E',        'C',          'A',              '-',              'A',      'A',            '4',           'Y',                  'Y',               'Y',                  'Y',             'Y',                  'Y',              'O',                             '99',                      '999',               '999',                      '999',                          '999',                   '999',                    '999',                  '999',                   '999',                     '999',                      'EF-EB',      '-',            '34.0522',  '118.2437'],
        ['3337743',                                            1900,                                         '478242',   '0453',                    '5',       '0',        '1949',               '0',               '8',       '0',           None,               None,           '43T1',      'HOXIE_AV',                        'IMPERIAL_HWY',  400.02,       'S',       True,         'A',       None,      True,                    '123',           99,                80,          'B',          'B',             38,            'I',           4,                 'E',             False,    4,                  0,              0,               1,           'E',                      'W',                '08',                   22107,         None,                     'N',         'E',               'J',                         'E',        'C',          'A',              None,             'A',      'A',            '4',           True,                 True,              True,                 True,            True,                 True,             'O',                             None,                      999,                 999,                        999,                            999,                     999,                      999,                    999,                     999,                       999,                        'EF-EB',      None,           34.0522,    -118.2437, "2007-08-21", "09:10:00", "2008-02-14"],
    ),
    (
        #Case_ID                 Collision_Year  Process_Date  Jurisdiction  Collision_Date  Collision_Time  Officer_ID  Reporting_District  DOW    CHP_Shift  Population  County_City_Location  Special_Condition  Beat_Type  CHP_Beat_Type  City_Division_LAPD  CHP_Beat_Class  Beat_Number  Primary_Road                       Secondary_Road   Distance      Direction  Intersection  Weather_1  Weather_2  State_Highway_Indicator  Caltrans_County  Caltrans_District  State_Route  Route_Suffix  Postmile_Prefix  Postmile       Location_Type  Ramp_Intersection  Side_Of_Highway  Tow_Away  Collision_Severity  Killed_Victims  Injured_Victims  Party_Count  Primary_Collision_Factor  PCF_Violation_Code  PCF_Violation_Category  PCF_Violation  PCF_Violation_Subsection  Hit_And_Run  Type_Of_Collision  Motor_Vehicle_Involved_With  Ped_Action  Road_Surface  Road_Condition_1  Road_Condition_2  Lighting  Control_Device  CHP_Road_Type  Pedestrian_Collision  Bicycle_Collision  Motorcycle_Collision  Truck_Collision  Not_Private_Property  Alcohol_Involved  Statewide_Vehicle_Type_At_Fault  CHP_Vehicle_Type_At_Fault  Severe_Injury_Count  Other_Visible_Injury_Count  Complaint_Of_Pain_Injury_Count  Pedestrian_Killed_Count  Pedestrian_Injured_Count  Bicyclist_Killed_Count  Bicyclist_Injured_Count  Motorcyclist_Killed_Count  Motorcyclist_Injured_Count  Primary_Ramp  Secondary_Ramp  Latitude    Longitude
        ['90180431',             '2015',         '20160516',   '9535',       '20151021',     '1635',         '021169',   '',                 '3',   '2',       '-',        '1948',               '3',               '-',       '-',           'A',                '2',            '-',         'I-710_(LONG_BEACH_FREEWAY)_N/B',  'FLORAL_DR',     '-',          '-',       '-',          '',        '-',       '-',                     '',              '',                '',          '',           '',              '',            '',            '',                '',              '',       '1',                '-',            '-',             '',          '-',                      '-',                '-',                   '-',           '-',                      'M',         '-',               '-',                         '-',        '-',          '-',              '-',              '-',      '-',            '',            '',                   '',                '',                   '',              '',                   '',               '-',                             '-',                       '-',                 '-',                        '-',                            '-',                     '-',                      '-',                    '-',                     '-',                       '-',                        '-',          '-',            '',         ''],
        ['90180431',                                           9535,                                         '021169',   None,                      '2',       None,       '1948',               '3',               None,      None,          'A',                '2',            None,        'I-710_(LONG_BEACH_FREEWAY)_N/B',  'FLORAL_DR',     None,         None,      None,         None,      None,      None,                    None,            None,              None,        None,         None,            None,          None,          None,              None,            None,     1,                  None,           None,            None,        None,                     None,               None,                   None,          None,                     'M',         None,              None,                        None,       None,         None,             None,             None,     None,           None,          None,                 None,              None,                 None,            None,                 None,             None,                            None,                      None,                None,                       None,                           None,                    None,                     None,                   None,                    None,                      None,                       None,         None,           None,       None, "2015-10-21", "16:35:00", "2016-05-16"],
    ),
)

def test_victimrows():
    for row, answer in ROWS:
        c = CollisionRow(row)
        assert c.values == answer
