from enum import Enum, unique

@unique
class Make(Enum):

    ACADIAN                 = "Acadian"
    ACURA                   = "Acura"
    ALFA_ROMERO             = "Alfa Romera"
    AMC                     = "American Motors"
    AUDI                    = "Audi"
    AUTOCAR                 = "Autocar"
    BENTLEY                 = "Bentley"
    BLUEBIRD                = "Bluebird"
    BMW                     = "BMW"
    BUICK                   = "Buick"
    CADILLAC                = "Cadillac"
    CHEVROLET               = "Chevrolet"
    CHRYSLER                = "ChrysleR"
    CROWN                   = "Crown"
    DAEWOO                  = "Daewoo"
    DATSUN                  = "Datsun"
    DODGE                   = "Dodge"
    DUCATI                  = "Ducati"
    FERRARI                 = "Ferrari"
    FIAT                    = "Fiat"
    FORD                    = "Ford"
    FREIGHTLINER            = "Freightliner"
    GEO                     = "Geo"
    GILLIG                  = "Gillig"
    GMC                     = "GMC"
    GRUMMAN                 = "Grumman"
    HARLEY                  = "Harley-Davidson"
    HINO                    = "Hino"
    HONDA                   = "Honda"
    HUMMER                  = "Hummer"
    HYUNDAI                 = "Hyundai"
    INFINITI                = "Infiniti"
    INTERNATIONAL_HARVESTER = "International Harvester"
    ISUZU                   = "Isuzu"
    JAGUAR                  = "Jaguar"
    JEEP                    = "Jeep"
    JOHN_DEERE              = "John Deere"
    KAWASAKI                = "Kawasaki"
    KENWORTH                = "Kenworth"
    KIA                     = "Kia"
    LAND_ROVER              = "Land Rover"
    LEXUS                   = "Lexus"
    LINCOLN                 = "Lincoln"
    MACK                    = "Mack"
    MASERATI                = "Maserati"
    MAZDA                   = "Mazda"
    MERCEDES_BENZ           = "Mercedes-Benz"
    MERCURY                 = "Mercury"
    MINI                    = "Mini"
    MITSUBISHI              = "Mitsubishi"
    NISSAN                  = "Nissan"
    NONE                    = None
    OLDSMOBILE              = "Oldsmobile"
    PETERBILT               = "Peterbilt"
    PETERBILT               = "Peterbilt"
    PLYMOUTH                = "Plymouth"
    PONTIAC                 = "Pontiac"
    PORSCHE                 = "Porsche"
    RAM                     = "Ram"
    SAAB                    = "Saab"
    SATURN                  = "Saturn"
    SCION                   = "Scion"
    SCHWINN                 = "Schwinn"
    SMART                   = "Smart"
    STERLING                = "Sterling"
    SUBARU                  = "Subaru"
    SUZUKI                  = "Suzuki"
    TESLA                   = "Tesla"
    THOMAS                  = "Thomas"
    TOYOTA                  = "Toyota"
    TREK                    = "Trek"
    TRIUMPH                 = "Triumph"
    VESPA                   = "Vespa"
    VOLKSWAGEN              = "Volkswagen"
    VOLVO                   = "Volvo"
    WHITE                   = "White"
    WINNEBAGO               = "Winnebago"
    YAMAHA                  = "Yamaha"


MAKE_MAP = {
    "FORD": Make.FORD,
    "TOYOTA": Make.TOYOTA,
    "HONDA": Make.HONDA,
    "CHEVROLET": Make.CHEVROLET,
    "NISSAN": Make.NISSAN,
    "DODGE": Make.DODGE,
    "GMC": Make.GMC,
    "BMW": Make.BMW,
    "MERCEDES-BENZ": Make.MERCEDES_BENZ,
    "VOLKSWAGEN": Make.VOLKSWAGEN,
    "MAZDA": Make.MAZDA,
    "LEXUS": Make.LEXUS,
    "CHRYSLER": Make.CHRYSLER,
    "ACURA": Make.ACURA,
    "JEEP": Make.JEEP,
    "HYUNDAI": Make.HYUNDAI,
    "MITSUBISHI": Make.MITSUBISHI,
    "KIA": Make.KIA,
    "CHEV": Make.CHEVROLET,
    "TOYO": Make.TOYOTA,
    "HOND": Make.HONDA,
    "PONTIAC": Make.PONTIAC,
    "TOYT": Make.TOYOTA,
    "SATURN": Make.SATURN,
    "BUICK": Make.BUICK,
    "VOLVO": Make.VOLVO,
    "CADILLAC": Make.CADILLAC,
    "MERCURY": Make.MERCURY,
    "FREIGHTLINER": Make.FREIGHTLINER,
    "NISS": Make.NISSAN,
    "INFINITI": Make.INFINITI,
    "SUBARU": Make.SUBARU,
    "OLDSMOBILE": Make.OLDSMOBILE,
    "LINCOLN": Make.LINCOLN,
    "AUDI": Make.AUDI,
    "PLYMOUTH": Make.PLYMOUTH,
    "PETERBILT": Make.PETERBILT,
    "MISCELLANEOUS": Make.NONE,
    "INTERNATIONAL HARVESTER": Make.INTERNATIONAL_HARVESTER,
    "SUZUKI": Make.SUZUKI,
    "DATSUN/NISSAN": Make.NISSAN,
    "HYUN": Make.HYUNDAI,
    "ISUZU": Make.ISUZU,
    "DODG": Make.DODGE,
    "HARLEY-DAVIDSON": make.HARLEY,
    "OTHER - AUTO": Make.NONE,
    "VOLK": Make.VOLKSWAGEN,
    "KENWORTH": Make.KENWORTH,
    "YAMAHA": Make.YAMAHA,
    "SCION": Make.SCION,
    "OTHER - BUS": Make.NONE,
    "NOT STATED": Make.NONE,
    "OTHER - TRUCK": Make.NONE,
    "KAWASAKI": Make.KAWASAKI,
    "JAGUAR": Make.JAGUAR,
    "OTHER DOMESTICS": Make.NONE,
    "MERZ": Make.MERCEDES_BENZ,
    "MAZD": Make.MAZDA,
    "CHRY": Make.CHEVROLET,
    "SUBA": Make.SUBARU,
    "MERB": Make.MERCEDES_BENZ,
    "LAND ROVER": Make.LAND_ROVER,
    "FREI": ,
    "CHEVY": Make.CHEVROLET,
    "PORSCHE": Make.PORSCHE,
    "OTHER FOREIGN": Make.NONE,
    "LEXU": Make.LEXUS,
    "ACUR": Make.ACURA,
    "LEXS": Make.LEXUS,
    "FRHT": Make.FREIGHTLINER,
    "INFI": Make.INIFINIT,
    "MINI": Make.MINI,
    "MITS": Make.MITSUBISHI,
    "SAAB": Make.SAAB,
    "PTRB": Make.PETERBILT,
    "CADI": Make.CADILLAC,
    "VOLV": Make.VOLVO,
    "MERCEDES BENZ": Make.MERCEDES_BENZ,
    "OTHER - PICKUP": Make.NONE,
    "MACK": Make.MACK,
    "DAEWOO": Make.DAEWOO,
    "RAM": Make.RAM,
    "OTHER - MOTORCYCLE": Make.NONE,
    "DATSUN": Make.DATSUN,
    "HINO": Make.HINO,
    "UNKNOWN": Make.NONE,
    "INTL": Make.NONE,
    "HARL": Make.HARLEY,
    "GILLIG (BUS)": Make.GILLIG,
    "FIAT": Make.FIAT,
    "PONT": Make.PONTIAC,
    "LINC": Make.LINCOLN,
    "BLUEBIRD (BUS)": Make.BLUEBIRD,
    "KW": ,
    "HUMMER": Make.HUMMER,
    "YAMA": Make.YAMAHA,
    "BUIC": Make.BUICK,
    "STERLING": Make.STERLING,
    "PETE": Make.PETERBILT,
    "THOMAS (BUS)": Make.THOMAS,
    "HD": Make.HARLEY,
    "INTE": ,
    "KENW": Make.KENWORTH,
    "MERC": Make.MERCURY,
    "TESLA": Make.TESLA,
    "OTHER - MOTORHOME": Make.NONE,
    "WHITE": Make.WHTIE,
    "ACADIAN": Make.ACADIAN,
    "DUCATI (MOTORCYCLE)": Make.DUCATI,
    "VOLKS": Make.VOLKSWAGEN,
    "CHEVROLE": Make.CHEVROLET,
    "OTHER - DOMESTIC": Make.NONE,
    "PORS": Make.PORSCHE,
    "TRIUMPH": Make.TRIUMPH,
    "SCIO": Make.SCION,
    "AMERICAN MOTORS (AMC)": Make.AMC,
    "STRN": Make.SATURN,
    "SATU": Make.SATURN,
    "SUZU": Make.SUZUKI,
    "VW": Make.VOLKSWAGEN,
    "WHITE GMC": Make.GMC,
    "KAWA": Make.KAWASAKI,
    "OTHER - MOPED": Make.NONE,
    "LAND": Make.LAND_ROVER,
    "TOYOT": Make.TOYOTA,
    "AMERICAN MOTORS": Make.AMC,
    "JAGU": Make.JAGUAR,
    "SUZI": Make.SUZUKI,
    "ISUZ": Make.ISUZU,
    "TESL": Make.TESLA,
    "GRUMMAN": Make.GRUMMAN,
    "TSMR": Make.TESLA,
    "TOY": Make.TOYOTA,
    "AUTOCAR": Make.AUTOCAR,
    "OLDS": Make.OLDSMOBILE,
    "UNK": Make.NONE,
    "KAWK": Make.KAWASAKI,
    "LNDR": Make.LAND_ROVER,
    "ROVER": Make.LAND_ROVER,
    "VESPA": Make.VESPA,
    "MNNI": Make.MINI,
    "SMART": Make.SMART,
    "OTHER - SCHOOL BUS": Make.NONE,
    "BLUE": Make.BLUEBIRD,
    "CROWN (BUS)": MAKE.CROWN,
    "ISU": Make.ISUZU,
    "CHRYS": Make.CHRYSLER,
    "MERCEDES": Make.MERCEDES,
    "WINNEBAGO": Make.WINNEBAGO,
    "INTER": Make.INTERNATIONAL_HARVESTER,
    "NISSA": Make.NISSAN,
    "JOHN DEERE": Make.JOHN_DEERE,
    "SPCNS (SPL CONSTRUCTED VEH)": ,
    "PETER": Make.PETERBILT,
    "INFINITY": Make.Infiniti,
    "NABORS": ,
    "UD": ,
    "MASERATI": Make.MASERATI,
    "GEO": Make.GEO,
    "PLYM": Make.PLYMOUTH,
    "WESTERN TRUCKS": ,
    "INFIN": Make.INFINITI,
    "STRICKLAND": ,
    "KTM": ,
    "HYUND": Make.HYUNDAI,
    "HON": Make.HONDA,
    "BENTLEY": Make.BENTLEY,
    "FERRARI": Make.FERRARI,
    "THOMAS": MAKE.THOMAS,
    "HUMM": Make.HUMMER,
    "TREK": Make.TREK,
    "MASE": Make.MASERATI,
    "HODAKA (MOTORCYCLE)": ,
    "FREIGHT": Make.FREIGHTLINER,
    "DUCA": Make.DUCATI,
    "TRIU": Make.TRIUMPH,
    "NIS": Make.NISSAN,
    "ALFA ROMERO": Make.ALFA_ROMERO,
    "JOHN": Make.JOHN_DEERE,
    "HARLEY": Make.HARLEY,
    "INTERNAT": Make.INTERNATIONAL_HARVESTER,
    "CHEVR": Make.CHEVROLET,
    "DAIHATSU": ,
    "TIOGA": ,
    "SCHWINN": Make.SCHWINN,
    "WABASH": ,
    "THOMA": Make.THOMAS,
    "HYU": Make.HYUNDAI,
    "OTHER - ATV": Make.NONE,
    "THOB": ,
    "MITSU": Make.MITSUBISHI,
    "MCI": ,
    "VANCO": ,
    "PEUGEOT": ,
    "AUTC": ,
    "FOR": ,
    "INDIAN (MOTORCYCLE)": ,
    "AMERICAN LA FRANCE": ,
    "STANDARD": ,
    "FRGHT": ,
    "SMRT": ,
    "KTMX": ,
    "HUFFY": ,
    "FRH": ,
    "ROLLS ROYCE": ,
    "SPECIALI": ,
    "MONACO": ,
    "LEX": ,
    "GIANT": ,
    "PACE ARROW": ,
    "STRG": ,
    "MONGOOSE": ,
    "CHE": ,
    "MOTO GUZZI": ,
    "SUBAR": ,
    "NABI": ,
    "FREIGHTL": ,
    "HYUNDA": ,
    "VOLKSWAG": ,
    "FRT": ,
    "MBZ": ,
    "WSTR": ,
    "WINN": ,
    "PETERBIL": ,
    "BICYCLE": ,
    "DUCATI": ,
    "LOTUS": ,
    "GOLD RUSH": ,
    "BLBRD": ,
    "TOYTA": ,
    "COACHMAN": ,
    "MISSISSIPPI": ,
    "WEST": ,
    "MITSUBIS": ,
    "VICTORY": ,
    "MAZ": ,
    "LAMBORGHINI": ,
    "CHAMPION": ,
    "KENT": ,
    "MG": ,
    "ITASCO": ,
    "BLUEBIRD": ,
    "CHEVRO": ,
    "CAT": ,
    "BOUNDER": ,
    "STER": ,
    "TRUM": ,
    "SOUTHWIND": ,
    "FLAIR": ,
    "SPCN": ,
    "HARLEY DAVIDSON": ,
    "GENESIS": ,
    "CANNONDA": ,
    "THOM": ,
    "ASTON MARTIN": ,
    "AUTO": ,
    "BENT": ,
    "GILL": ,
    "ALFR": ,
    "TOYOTA/": ,
    "SAA": ,
    "INFINI": ,
    "BLU": ,
    "NAVISTAR": ,
    "FREIGH": ,
    "OSHKOSH": ,
    "POLARIS": ,
    "CONQUEST": ,
    "SUBU": ,
    "KUBOTA": ,
    "DUCAT": ,
    "INDIAN": ,
    "ALLEGRO": ,
    "THMS": ,
    "DATS": ,
    "CUSHMAN": ,
    "SPECIAL": ,
    "SPCNS": ,
    "KME": ,
    "ALFA": ,
    "WANCO": ,
    "MARMON HARRINGTON": ,
    "DOD": ,
    "CHEVROL": ,
    "SAFARI": ,
    "HONDA/": ,
    "AUSTIN": ,
    "DIAMOND REO": ,
    "FRI": ,
    "LINDE": ,
    "FORD/": ,
    "WAYNE": ,
    "HONA": ,
    "HEIL": ,
    "GRUM": ,
    "ALFA GOLD": ,
    "UDXX": ,
    "GILLI": ,
    "TRACTOR": ,
    "MER": ,
    "INDI": ,
    "FUJI": ,
    "SUB": ,
    "SEDAN": ,
    "MASSEY FERGUSON": ,
    "PONTI": ,
    "UNKOWN": ,
    "ELDO": ,
    "NFLYR": ,
    "TITAN": ,
    "FTL": ,
    "TOTY": ,
    "AMER": ,
    "MITCHELL": ,
    "ICCOR": ,
    "CASE": ,
    "HUSQVARNA": ,
    "VANHOOL": ,
    "STRC": ,
    "HOLIDAY RAMBLER": ,
    "BLUEB": ,
    "ORION": ,
    "INTERN": ,
    "INDUSTRIAL & MUNICIPAL ENGRG": ,
    "ELDOR": ,
    "DOGE": ,
    "TRUCK": ,
    "TERBERG": ,
    "LANCIA": ,
    "CERVELO": ,
    "BUELL": ,
    "APRILIA": ,
    "ACU": ,
    "ROADMAST": ,
    "DAEW": ,
    "BMX": ,
    "RALEIGH": ,
    "IVECO": ,
    "/": ,
    "HYN": ,
    "SUNBEAM": ,
    "MERCU": ,
    "STUDEBAKER": ,
    "JAGA": ,
    "GILLIG": ,
    "STOUGHTON": ,
    "TOYTO": ,
    "FERR": ,
    "BWM": ,
    "PIERCE": ,
    "LAND ROV": ,
    "PTRBLT": ,
    "PREVOST": ,
    "MAGNA": ,
    "KAWI": ,
    "FRGH": ,
    "FREIG": ,
    "NEXT": ,
    "NEW HOLL": ,
    "CHVY": ,
    "NISSAN/": ,
    "SATUR": ,
    "TOTOTA": ,
    "HYPER": ,
    "HONEY": ,
    "THOR": ,
    "NEWFL": ,
    "DOG": ,
    "CAN-AM": ,
    "MAGIRUS": ,
    "BATAVUS (MOPED)": ,
    "INTERNA": ,
    "RALLYE JAMBOREE": ,
    "FRTL": ,
    "BB": ,
    "MITZ": ,
    "IHC": ,
    "FHRT": ,
    "BLUB": ,
    "THOMPSON BROTHERS": ,
    "FLEETWOO": ,
    "VCTY": ,
    "TOYTOA": ,
    "FELT": ,
    "RENAULT": ,
    "INTERNATIONAL": ,
    "FRGT": ,
    "KENWO": ,
    "HYTR": ,
    "GT": ,
    "PORT": ,
    "BIANCHI": ,
    "PUCH (MOPED)": ,
    "LINCOL": ,
    "INFINIT": ,
    "GILG": ,
    "FRIE": ,
    "VOL": ,
    "CHR": ,
    "LINCO": ,
    "COMMERCIAL VEHICLES": ,
    "VC SECTION 20002(A)": ,
    "FRTH": ,
    "FRG": ,
    "UNKN": ,
    "PREV": ,
    "TRINITY": ,
    "PACIFIC COACH": ,
    "TOYOYA": ,
    "HARLE": ,
    "EXCALIBUR": ,
    "PTBR": ,
    "LAMB": ,
    "CHEV.": ,
    "CADIL": ,
    "TOYT.": ,
    "PETERBUI": ,
    "CHEV/": ,
    "CANA": ,
    "AUD": ,
    "WESTERN": ,
    "SCOTT": ,
    "OSHK": ,
    "HARO": ,
    "CHEVY/": ,
    "COMMANDER": ,
    "INF": ,
    "PETERBLT": ,
    "MOTO": ,
    "LANDROVE": ,
    "CROWN": ,
    "STAR": ,
    "JAMEE": ,
    "HUSQ": ,
    "APOLLO": ,
    "TRANS": ,
    "DODGE/": ,
    "DODE": ,
    "CHEVROLT": ,
    "YAMAH": ,
    "SHASTA": ,
    "MAZA": ,
    "BIKE": ,
    "TOTO": ,
    "TOMO": ,
    "SCHWIN": ,
    "PETERB": ,
    "NEWFLYER": ,
    "HARLEY D": ,
    "GMC (GENERAL MOTORS)": ,
    "MARIN": ,
    "COAC": ,
    "BLUBD": ,
    "ASTO": ,
    "SPEC": ,
    "JOHN DEE": ,
    "ROCKWOOD": ,
    "PIERC": ,
    "MIT": ,
    "WHGM": ,
    "TOYA": ,
    "OPEL": ,
    "ALLE": ,
    "MIN": ,
    "KENWOR": ,
    "CEHV": ,
    "SMAR": ,
    "NFLY": ,
    "SEMI": ,
    "NISSN": ,
    "APRI": ,
    "MONA": ,
    "BROUGHAM": ,
    "TOYTOTA": ,
    "PETR": ,
    "PANTERA": ,
    "NISA": ,
    "MIFU": ,
    "MERCEDEZ": ,
    "FLEET": ,
    "PTB": ,
    "PETERBUILT": ,
    "MCLAREN": ,
    "INT": ,
    "WORKH": ,
    "PACE": ,
    "KINGSLEY": ,
    "FORD /": ,
    "CHV": ,
    "BOBKO": ,
    "UKNOWN": ,
    "TRIUM": ,
    "TOYOA": ,
    "CITROEN": ,
    "CHEY": ,
    "4WN": ,
    "SPART": ,
    "PINARELL": ,
    "OVERLAND": ,
    "INTNL": ,
    "IC": ,
    "GNSI": ,
    "DIAMOND": ,
    "DELOREAN": ,
    "ZERO": ,
    "VANHO": ,
    "SHIMANO": ,
    "NISAN": ,
    "VESP": ,
    "ROLL": ,
    "MCIN": ,
    "MASS": ,
    "TELSA": ,
    "SUV": ,
    "SPORTS COACH": ,
    "SPCLZD": ,
    "CHRYSL": ,
    "UTIL": ,
    "TOYO /": ,
    "PACIFIC": ,
    "HUYN": ,
    "ELDORADO": ,
    "BULTACO (MOTORCYCLE)": ,
    "ELECTRA": ,
    "MONON": ,
    "MCLA": ,
    "ITAS": ,
    "FRGHTLNR": ,
    "RAVENS": ,
    "GRUMMAN MOTOR HOME": ,
    "FRHTLNR": ,
    "WRKCC": ,
    "WESCO": ,
    "SPECIALIZED": ,
    "SETRA": ,
    "NEW FLYER": ,
    "MILLER": ,
    "LROV": ,
    "HYND": ,
    "GLOBAL": ,
    "FRIEGHT": ,
    "BMC": ,
    "ACRUA": ,
    "ZASTAVA": ,
    "VOVLO": ,
    "UNKN/": ,
    "NWFLR": ,
    "MOTIV": ,
    "JAMIS": ,
    "HODNA": ,
    "GMC/": ,
    "TIFFIN": ,
    "SMEAL": ,
    "RAZOR": ,
    "MERCE": ,
    "LANDOLL": ,
    "INFINTI": ,
    "FRTLNR": ,
    "DIAMONDB": ,
    "COLNAGO": ,
    "VOGUE": ,
    "VNHL": ,
    "PTRBILT": ,
    "NISSIAN": ,
    "NISHIKI": ,
    "MITSUB": ,
    "JEE": ,
    "JAYCO": ,
    "FIXIE": ,
    "CHEV /": ,
    "CANNON": ,
    "AVION": ,
    "VAN": ,
    "TIOG": ,
    "TESLA MOTORS": ,
    "RANGE": ,
    "HOND /": ,
    "CUSTOM": ,
    "ROVE": ,
    "RANGE RO": ,
    "MAZADA": ,
    "JENSEN": ,
    "HOLI": ,
    "HME": ,
    "HARLO": ,
    "EXECUTIVE": ,
    "BMW/": ,
    "APRIL": ,
    "20002 VC": ,
    "WSTS": ,
    "VOLS": ,
    "SATR": ,
    "PICKUP": ,
    "MAJES": ,
    "KENWOOD": ,
    "KAWAS": ,
    "IZUZU": ,
    "FBG": ,
    "UNK /": ,
    "PONTIA": ,
    "MORGAN": ,
    "JEEP/": ,
    "INTR": ,
    "HYUNDIA": ,
    "GMA": ,
    "FREIGHTLINER CORP": ,
    "CHEVE": ,
    "BLUE BIR": ,
    "APRILLA": ,
    "AIRBUS": ,
    "UNIVEGA": ,
    "STARC": ,
    "PET": ,
    "NEWMAR": ,
    "MRZ": ,
    "MINNI": ,
    "JAMBO": ,
    "HODA": ,
    "BUIK": ,
    "20002": ,
    "WNBGO": ,
    "WINNE": ,
    "VOLKSWGN": ,
    "UNK.": ,
    "TRAILER": ,
    "SIMCA": ,
    "POLA": ,
    "NISS /": ,
    "MNN": ,
    "HARLEY-D": ,
    "CRANE": ,
    "CHAM": ,
    "CADILL": ,
    "BLUBR": ,
    "VANH": ,
    "THOMS": ,
    "POLS": ,
    "ORBEA": ,
    "MOUNTAIN VALLEY": ,
    "MOTOBECA": ,
    "MASER": ,
    "KHS": ,
    "JAGUA": ,
    "FROD": ,
    "CAR": ,
    "CAD": ,
    "ARGOSY": ,
    "VNHO": ,
    "SMA": ,
    "SATRUN": ,
    "PORCHE": ,
    "LOOK": ,
    "LIN": ,
    "FIA": ,
    "CANONDAL": ,
    "BUEL": ,
    "BLB": ,
    "ZNEN": ,
    "YAH": ,
    "VANC": ,
    "SPRINT": ,
    "SPARTAN": ,
    "PIRC": ,
    "NOVARA": ,
    "MORRIS": ,
    "MADZA": ,
    "LOADCRAFT": ,
    "KYMCO": ,
    "KIS": ,
    "GM": ,
    "COLNS": ,
    "CHEC": ,
    "CADILAC": ,
    "ALFA ROMEO": ,
    "VAN HOOL": ,
    "PRTB": ,
    "NISSSAN": ,
    "MERCUR": ,
    "LAN": ,
    "JONWAY": ,
    "IZUSU": ,
    "ICCRP": ,
    "GRUMAN": ,
    "FRIGHT": ,
    "COACH": ,
    "CANYON": ,
    "CANAM": ,
    "BROCKWAY": ,
    "BOUND": ,
    "WSTST": ,
    "WHITE VOLVO": ,
    "SPNR": ,
    "PREVO": ,
    "MITSUBI": ,
    "MERS": ,
    "MAJE": ,
    "JAG": ,
    "INFINTY": ,
    "WABA": ,
    "US INDUSTRIES": ,
    "SUBR": ,
    "SUBARU/": ,
    "STARCRAF": ,
    "SPCLIZED": ,
    "REDLINE": ,
    "PORC": ,
    "PIAGGIO": ,
    "OLDSMOBI": ,
    "NATIONAL": ,
    "KONA": ,
    "HYOS": ,
    "HYNDAI": ,
    "HIONDA": ,
    "GE": ,
    "FLORY": ,
    "F0RD": ,
    "BENSON": ,
    "AMERICAN": ,
    "VPG": ,
    "TOYT/": ,
    "SUBURU": ,
    "SSR": ,
    "PORSHE": ,
    "PORSCH": ,
    "PORSC": ,
    "MICARGI": ,
    "LOTU": ,
    "LANCE": ,
    "KIA/": ,
    "INTERNTL": ,
    "CROW": ,
    "CROSS COUNTRY": ,
    "BUI": ,
    "BENZ": ,
    "ARCA": ,
    "TOTOYA": ,
    "SWIND": ,
    "STERL": ,
    "RIDLEY": ,
    "PREO": ,
    "NEW FLYE": ,
    "MASI": ,
    "JAY": ,
    "ICRP": ,
    "GROVE": ,
    "EAGLE": ,
    "CARSON": ,
    "BEACH": ,
    "ACURA/": ,
    "ACUA": ,
    "VOLKSWA": ,
    "VNHOL": ,
    "VAUXHALL": ,
    "TOYT /": ,
    "SUZUK": ,
    "SPECLZD": ,
    "SOUT": ,
    "SOLAR": ,
    "PTBL": ,
    "NAVI": ,
    "N/A": ,
    "MAZDA/": ,
    "LEXUS/": ,
    "LANDR": ,
    "KENWORT": ,
    "HYUNDI": ,
    "HSI": ,
    "FREI /": ,
    "EMD": ,
    "CLUB CAR": ,
    "CHYSLER": ,
    "CATER": ,
    "BIG RIG": ,
    "BERTON": ,
    "AVENTON": ,
    "WRKH": ,
    "WHIT": ,
    "VOLVO/": ,
    "VICT": ,
    "TOT": ,
    "THRUSTER": ,
    "TEMSA": ,
    "SURLY": ,
    "SATRN": ,
    "S-WORKS": ,
    "RORO": ,
    "PTRB/": ,
    "NDMC": ,
    "METEOR": ,
    "MBLT": ,
    "HYUNDAI/": ,
    "HYUDAI": ,
    "HUYNDAI": ,
    "GARY FIS": ,
    "FRHI": ,
    "EL DORAD": ,
    "EAGL": ,
    "DAIMLERCHRYSLER": ,
    "CHEB": ,
    "BOUN": ,
    "AUTOC": ,
    "WORKHORS": ,
    "WORK": ,
    "WINNEBAG": ,
    "UNKNOWN/": ,
    "UHAU": ,
    "TYMCO": ,
    "THRONE": ,
    "PREDATOR": ,
    "PENSKE": ,
    "NWFLY": ,
    "MINN": ,
    "LES": ,
    "LEMOND": ,
    "ITASCA": ,
    "HYOSUNG": ,
    "HNDA": ,
    "GDAN": ,
    "FRUE": ,
    "FREIT": ,
    "FOURW": ,
    "FOCUS": ,
    "DURABILT": ,
    "COLLINS": ,
    "COLEMAN": ,
    "CHECY": ,
    "CARSN": ,
    "BUGATTI": ,
    "BEAVER": ,
    "6KU": ,
    "VANHL": ,
    "TRIUMP": ,
    "SYM": ,
    "STRCR": ,
    "SPECIALZ": ,
    "SOUTH": ,
    "PORSH": ,
    "PEDEGO": ,
    "MCKT": ,
    "LINKB": ,
    "KRYST": ,
    "JDEER": ,
    "ITASC": ,
    "INTL.": ,
    "GRANITE": ,
    "GLAV": ,
    "GILIG": ,
    "FRUEH": ,
    "FRGHT.": ,
    "DUC": ,
    "CHRS": ,
    "CANN": ,
    "BMV": ,
    "B.M.W.": ,
    "YUGO": ,
    "WOHRS": ,
    "WNBG": ,
    "WILLY": ,
    "VOLVE": ,
    "VOLKS/": ,
    "V W": ,
    "UNK/": ,
    "TMC": ,
    "TAO": ,
    "SUZ": ,
    "SUBUR": ,
    "SEVEN": ,
    "SEROTTA": ,
    "PETRBILT": ,
    "NONE": ,
    "MAJESTIC": ,
    "LIME": ,
    "LEXSUS": ,
    "KEN": ,
    "KAWASA": ,
    "HYUD": ,
    "GLBEN": ,
    "FREIGHT LINER": ,
    "EZGO": ,
    "DINA": ,
    "DIAM": ,
    "CRYS": ,
    "BLUBIRD": ,
    "BIRD": ,
    "UTILITY": ,
    "UKN": ,
    "TREX": ,
    "THMC": ,
    "STLG": ,
    "STARR": ,
    "SEAGRAVE": ,
    "SACHS (MOPED)": ,
    "ROOTIERS": ,
    "POR": ,
    "POLAR": ,
    "PIAGG": ,
    "PIAG": ,
    "MZD": ,
    "MURRAY": ,
    "MNACO": ,
    "MERLIN": ,
    "LITESPEE": ,
    "KW/": ,
    "JEEF": ,
    "HONDA`": ,
    "HINDA": ,
    "HARLY": ,
    "GRUMM": ,
    "FRHTLINR": ,
    "FRET": ,
    "FITBIKE": ,
    "FIRMSTRO": ,
    "CHY": ,
    "CHRYLSER": ,
    "CARSO": ,
    "CANNONDL": ,
    "BMW /": ,
    "BLK": ,
    "BIGTX": ,
    "BAYSIDE": ,
    "ZIEM": ,
    "URAL": ,
    "TSLA": ,
    "TOYOTO": ,
    "TEREX": ,
    "SUZIKI": ,
    "SUSUKI": ,
    "SUBURA": ,
    "STR": ,
    "SPTN": ,
    "SCATTANT": ,
    "SATN": ,
    "SAFA": ,
    "ROADR": ,
    "ROADMSTR": ,
    "ROAD": ,
    "RETROSPE": ,
    "PON": ,
    "POCKET": ,
    "PETRB": ,
    "OTHL": ,
    "NISS/": ,
    "NEW": ,
    "MZB": ,
    "MNAC": ,
    "MEC": ,
    "LPRCN": ,
    "LAMO": ,
    "KODIAK": ,
    "HOMD": ,
    "HOLLAND": ,
    "GMV": ,
    "FRRV": ,
    "FRHT/": ,
    "FOURWIND": ,
    "FORF": ,
    "FIT": ,
    "EZ-GO": ,
    "DAMON": ,
    "CRCAR": ,
    "CHRYSLE": ,
    "CASCADIA": ,
    "CANNONDALE": ,
    "CADILLA": ,
    "BME": ,
    "BCA": ,
    "AUI": ,
    "ACCURA": ,
    "WST": ,
    "WILIER": ,
    "WHT": ,
    "VOVL": ,
    "VOLV /": ,
    "TOY0": ,
    "TIME": ,
    "THO": ,
    "TAOTAO": ,
    "SPRI": ,
    "SKIDOO": ,
    "SATURN/": ,
    "SANTA CR": ,
    "RAM/": ,
    "RAD": ,
    "PTR": ,
    "PTER": ,
    "PTBT": ,
    "PONI": ,
    "POL": ,
    "NIIS": ,
    "MZDA": ,
    "MOUNTAIN": ,
    "MITT": ,
    "MERB /": ,
    "MAGNUM": ,
    "LAFR": ,
    "JLG": ,
    "JAMBOREE": ,
    "INTRNTL": ,
    "INTL BTM": ,
    "INGS": ,
    "HYUN /": ,
    "HONDS": ,
    "HOND/": ,
    "HOMEMADE": ,
    "HILLMAN": ,
    "HARDROCK": ,
    "GENUINE": ,
    "GENISIS": ,
    "FWD": ,
    "FUSO": ,
    "FRIGH": ,
    "FREHT": ,
    "FREH": ,
    "FORS": ,
    "FORE": ,
    "FOD": ,
    "DYNO": ,
    "DODG /": ,
    "DIDGE": ,
    "DICO": ,
    "COOLSTER": ,
    "CENTURIO": ,
    "CEHVY": ,
    "BLU BIRD": ,
    "BEACH CRUISER": ,
    "ARGON": ,
    "APRLA": ,
    "AMTRA": ,
    "ZONG": ,
    "XXX": ,
    "WESTER": ,
    "WABAS": ,
    "VOLKSW": ,
    "VOKS": ,
    "VICTO": ,
    "VERTICAL": ,
    "USPS": ,
    "THRC": ,
    "THMSB": ,
    "SUNDAY": ,
    "SEGWAY": ,
    "SCWINN": ,
    "SCOOTER": ,
    "ROLLS": ,
    "ROADMASTER": ,
    "PUREFIX": ,
    "PURE FIX": ,
    "PTBLT": ,
    "PEUG": ,
    "PETRBLT": ,
    "MVAGU": ,
    "MISS": ,
    "MINI COOPER": ,
    "MERCED": ,
    "MAZDA 3": ,
    "MAICO": ,
    "LXS": ,
    "LLV": ,
    "LINK": ,
    "LEXIS": ,
    "KLEIN": ,
    "KAWASAK": ,
    "KAI": ,
    "JPEG": ,
    "JOHNS": ,
    "JAYC": ,
    "IZU": ,
    "ITALIKA": ,
    "HUNDAI": ,
    "GLOBA": ,
    "FRHT.": ,
    "FORR": ,
    "FOED": ,
    "FLTWD": ,
    "EZ GO": ,
    "DENALI": ,
    "CHRYLER": ,
    "CHALLENG": ,
    "CARRYON": ,
    "BUICK/": ,
    "BENTL": ,
    "BBIRD": ,
    "BAJA": ,
    "AUST": ,
    "ATHEY": ,
    "AMERI": ,
    "AM GEN": ,
    "ACAD": ,
    "20002(A)": ,
    "WILLYS": ,
    "WHIG": ,
    "WHIB": ,
    "VOLO": ,
    "VOLK /": ,
    "VLV": ,
    "VACON": ,
    "UTILI": ,
    "UNKNOW": ,
    "TRLMO": ,
    "TRANSIT": ,
    "TRAIL": ,
    "TOYTT": ,
    "TOYOYTA": ,
    "TOYOY": ,
    "TOMMASO": ,
    "TAOTA": ,
    "SUZUKI MC": ,
    "SUZK": ,
    "SUBI": ,
    "STUD": ,
    "SPECILIZ": ,
    "SATRU": ,
    "RDMASTER": ,
    "PVOS": ,
    "PONTIAC/": ,
    "PJ": ,
    "PBLT": ,
    "OMC": ,
    "NORTH AMERICAN BUS": ,
    "NIISS": ,
    "NIISAN": ,
    "NEWMA": ,
    "NEWHOLLA": ,
    "MITI": ,
    "MERZ /": ,
    "LIV": ,
    "LIC": ,
    "LANDRVR": ,
    "LA JOLLA": ,
    "KESTREL": ,
    "KARMA": ,
    "KABOTA": ,
    "K2": ,
    "JOHND": ,
    "INTRL": ,
    "INTN": ,
    "INTEL": ,
    "ICORP": ,
    "IC CORP": ,
    "HYUN/": ,
    "HYUAN": ,
    "HONDA /": ,
    "HARLEYD": ,
    "GULF": ,
    "GMC /": ,
    "GIRAR": ,
    "GARY": ,
    "FRE": ,
    "FRD": ,
    "FOUR WIN": ,
    "FORD`": ,
    "FLEEW": ,
    "EXEC": ,
    "EGIL": ,
    "CRYSLER": ,
    "COLUMBIA": ,
    "CARACI": ,
    "BUCK": ,
    "BMW`": ,
    "BIG TEX": ,
    "BEALL": ,
    "AZTEX": ,
    "AUTCR": ,
    "APRILLIA": ,
    "AMIGO": ,
    "AMG": ,
    "ALF": ,
    "AIRSTREA": ,
    "YAHAMA": ,
    "YAHA": ,
    "VOLKWAGE": ,
    "VOK": ,
    "VILANO": ,
    "VERMA": ,
    "UNKWN": ,
    "SUPER": ,
    "STATE": ,
    "SPCL": ,
    "SKI-DOO": ,
    "SHWINN": ,
    "SEAGR": ,
    "SE": ,
    "SANYA": ,
    "RV": ,
    "ROEN": ,
    "ROADTREK": ,
    "ROADRUNN": ,
    "RITCHEY": ,
    "RHINO": ,
    "REO": ,
    "PTRBL": ,
    "PRIUS": ,
    "PORCH": ,
    "PONITAC": ,
    "PB": ,
    "PARLEE": ,
    "OTMO": ,
    "OTBX": ,
    "NORTON": ,
    "NISSS": ,
    "NISAAN": ,
    "NINJA": ,
    "MTN BIKE": ,
    "MITS/": ,
    "MIST": ,
    "MERZ BNZ": ,
    "MAZAD": ,
    "MAXDA": ,
    "LYNSKEY": ,
    "LND RVR": ,
    "LICOLN": ,
    "LEXUX": ,
    "KYMC": ,
    "KWN": ,
    "KOMATSU": ,
    "KAWASKI": ,
    "JEEP /": ,
    "JACKRABB": ,
    "IRONHORS": ,
    "INT.": ,
    "INIFINIT": ,
    "INFIN/": ,
    "INFI /": ,
    "HYUNDAY": ,
    "HYUNDAU": ,
    "HORSE": ,
    "HONDAS": ,
    "HONAD": ,
    "HIND": ,
    "HAVOC": ,
    "GRUMANN": ,
    "GEN ELEC": ,
    "G E": ,
    "FRIEGH": ,
    "FOUR": ,
    "FLTWOOD": ,
    "FLT": ,
    "FLAI": ,
    "FISHER": ,
    "FERRA": ,
    "ELITE": ,
    "ELECTRIC": ,
    "EL DORADO INTL": ,
    "DYNACRAF": ,
    "DOLPHIN": ,
    "DOGDE": ,
    "DNAIR": ,
    "DIAM BAC": ,
    "DARK": ,
    "COMPACT": ,
    "COLL": ,
    "COLBC": ,
    "COE": ,
    "COBRA": ,
    "CHEVT": ,
    "CHEVRLET": ,
    "CCHMN": ,
    "BYD": ,
    "BRAU": ,
    "BH": ,
    "BAODI": ,
    "AVIGO": ,
    "APACHE": ,
    "AMTRAN": ,
    "AMEL": ,
    "3 AXLE": ,
    "________": ,
    "ZHONG": ,
    "ZHNG": ,
    "ZEMAN": ,
    "WRKHS": ,
    "WKHS": ,
    "WINDSOR": ,
    "WANC": ,
    "VOLT": ,
    "VOLK/": ,
    "VENTO": ,
    "TTECH": ,
    "TRLRT": ,
    "TRIPH": ,
    "TOYR": ,
    "TIFFI": ,
    "TIFF": ,
    "TEMS": ,
    "T0YOTA": ,
    "SUBRAU": ,
    "SPRINTER": ,
    "SKU": ,
    "SIEMENS": ,
    "SETR": ,
    "SALSA": ,
    "RSNBR": ,
    "ROLLS-ROYCE": ,
    "ROLE": ,
    "ROL": ,
    "ROCK": ,
    "REVOL": ,
    "RENA": ,
    "RANGEROV": ,
    "RALLYE": ,
    "QUINTANA": ,
    "PVOST": ,
    "PURE": ,
    "PTRBT": ,
    "PRROW": ,
    "PIONEER": ,
    "PIAGI": ,
    "NSSAN": ,
    "NORCO": ,
    "NISSAN`": ,
    "NASHBAR": ,
    "MOOTS": ,
    "MNICP": ,
    "MITTS": ,
    "MEZ": ,
    "MERZB": ,
    "LOGAN": ,
    "LMBO": ,
    "LINKBELT": ,
    "LINCON": ,
    "LINCOLN CONTINENTAL": ,
    "LINCL": ,
    "LEP": ,
    "LAPIERRE": ,
    "LANDRO": ,
    "KNWRTH": ,
    "KMFRT": ,
    "KIA /": ,
    "JEEEP": ,
    "ISZ": ,
    "INTRNL": ,
    "INTL/": ,
    "INTERN.": ,
    "INFIT": ,
    "IDAHO": ,
    "HYUNA": ,
    "HUMVEE": ,
    "HUMME": ,
    "HRAMB": ,
    "HOLIDAY": ,
    "HAIBIKE": ,
    "GREEN": ,
    "GMX": ,
    "GMS": ,
    "GLENDALE": ,
    "GIAN": ,
    "GAUNTLET": ,
    "G.E.": ,
    "FTWD": ,
    "FRGTLNR": ,
    "FREG": ,
    "FORT": ,
    "FORIV": ,
    "FOREST R": ,
    "FORES": ,
    "FORED": ,
    "FORC": ,
    "EONE": ,
    "ELEC": ,
    "DOLPH": ,
    "DODEG": ,
    "DODDGE": ,
    "DAIML": ,
    "DAIH": ,
    "COLLI": ,
    "CINELLI": ,
    "CIMC": ,
    "CHRYSTLE": ,
    "CHRSLER": ,
    "CHEV`": ,
    "CHEVOLET": ,
    "CHAOS": ,
    "CANNOND": ,
    "CALFEE": ,
    "CADI/": ,
    "BROCE": ,
    "BRIDGEST": ,
    "BRAUN": ,
    "BOBCAT": ,
    "BMS": ,
    "BETA": ,
    "AVALON": ,
    "AUIDI": ,
    "AUID": ,
    "ASSEMBLE": ,
    "APRILA": ,
    "ANCHEER": ,
    "ALUMA": ,
    "AIRST": ,
    "AIREX": ,
    "20002VC": ,
    "(UNK)": ,
    "YAMH": ,
    "YAM": ,
    "XTREME": ,
    "WORKHORSE CUSTOM": ,
    "WESTSTAR": ,
    "WESTE": ,
    "VULCAN": ,
    "VOLW": ,
    "VOLKW": ,
    "VOLD": ,
    "VOLAGI": ,
    "VM": ,
    "VITESSE": ,
    "VICTY": ,
    "VER": ,
    "URBAN": ,
    "UNNOWN": ,
    "UNKNWON": ,
    "UNKNWN": ,
    "TYOT": ,
    "TREK, INC.": ,
    "TRECK": ,
    "TRCTR": ,
    "TRAF": ,
    "TRAC": ,
    "TOYT/SCI": ,
    "TOYP": ,
    "TOYOTS": ,
    "THEURER": ,
    "SUBRA": ,
    "SUBARA": ,
    "STARCRFT": ,
    "SPECIAL CONSTRUCTION": ,
    "SPECALIZ": ,
    "SPE": ,
    "SPCLIZD": ,
    "SOUTHWIN": ,
    "SIERRA": ,
    "SEQUENCE": ,
    "SCHW": ,
    "ROADTECH": ,
    "RNG RVR": ,
    "RANGE ROVER": ,
    "PRTA": ,
    "PRIDE": ,
    "PREMIER": ,
    "PINARELO": ,
    "PIER": ,
    "PICK UP": ,
    "PHAT": ,
    "PETERBU": ,
    "PEDE": ,
    "PBT": ,
    "P2550": ,
    "OTHER": ,
    "NOMAD": ,
    "NISSI": ,
    "NEW FLYR": ,
    "MVAG": ,
    "MOTORIZE": ,
    "MORG": ,
    "MONG": ,
    "MIYATA": ,
    "MITU": ,
    "MISTU": ,
    "MINIBIKE": ,
    "MERD": ,
    "MERCEDE": ,
    "MERBNZ": ,
    "MERB.": ,
    "MAZDZ": ,
    "MAZDA 6": ,
    "MAHINDRA": ,
    "M/C": ,
    "LINCOLN/": ,
    "LEXS /": ,
    "LEXI": ,
    "LEADER": ,
    "LAND RVR": ,
    "KODIA": ,
    "KEYSTONE": ,
    "KAWAI": ,
    "JUMP": ,
    "JOHN DEER": ,
    "JETSON": ,
    "JEP": ,
    "JEEO": ,
    "ITNL": ,
    "ISUSU": ,
    "INIFI": ,
    "INIF": ,
    "INFINT": ,
    "INFINITE": ,
    "INDIA": ,
    "ICC": ,
    "HYUANDAI": ,
    "HYNU": ,
    "HUN": ,
    "HUFF": ,
    "HONE": ,
    "HOLID": ,
    "HAULMARK": ,
    "HARD": ,
    "H.D.": ,
    "GULFS": ,
    "GRY": ,
    "GRATD": ,
    "GRADALL": ,
    "GOTRAX": ,
    "GLOBE": ,
    "GENUI": ,
    "GENU": ,
    "GEN": ,
    "FRTLN": ,
    "FRNT": ,
    "FRIEGHTL": ,
    "FRHTLINE": ,
    "FREITLNR": ,
    "FORREST": ,
    "FLEETWD": ,
    "FIT BIKE": ,
    "FISKER": ,
    "FIRD": ,
    "FERRARA": ,
    "FABC": ,
    "EXTREME": ,
    "EVO": ,
    "ESTAB": ,
    "ELDRD": ,
    "EBR": ,
    "DYNA": ,
    "DEER": ,
    "DE ROSA": ,
    "DAWES": ,
    "DARGO": ,
    "CULT": ,
    "CRUISER": ,
    "CRICKETT": ,
    "CRAN": ,
    "COUNTRY": ,
    "COLN": ,
    "CO-OP": ,
    "CHRYST": ,
    "CHRYSER": ,
    "CHRY/": ,
    "CHEVRLT": ,
    "CHEVEY": ,
    "CHEROLET": ,
    "CHE V": ,
    "CHAMP": ,
    "CATI": ,
    "CAN AM": ,
    "CADD": ,
    "BWW": ,
    "BUCIK": ,
    "BLUBRD": ,
    "BLACK": ,
    "BIGTE": ,
    "AUT": ,
    "AUCT": ,
    "ASTON": ,
    "AMTRN": ,
    "AMCLP": ,
    "ALLEG": ,
    "ALLCO": ,
    "ADDCO": ,
    "ZIEMAN": ,
    "ZIEMA": ,
    "ZHEJIANG": ,
    "WSTRN": ,
    "WRKHR": ,
    "WOR": ,
    "WKHRS": ,
    "WINDS": ,
    "WESTERNS": ,
    "WEST STA": ,
    "WELL": ,
    "VOLV0": ,
    "VOLSWGN": ,
    "VOLLK": ,
    "VOLKWGN": ,
    "VOLCO": ,
    "VLVO": ,
    "VGARD": ,
    "VER-MAC": ,
    "V.W.": ,
    "USTRA": ,
    "UPLAND": ,
    "UNKNONW": ,
    "UHAUL": ,
    "UDMTR": ,
    "TYOTA": ,
    "TUFFY": ,
    "TUFBY": ,
    "TRUIMPH": ,
    "TRNTC": ,
    "TRIM": ,
    "TRIAX": ,
    "TOYY": ,
    "TOYOTOA": ,
    "TOYORA": ,
    "TOYOR": ,
    "TOYI": ,
    "TOYATA": ,
    "TOWNIE": ,
    "TOTYOTA": ,
    "THMAS": ,
    "TERRY": ,
    "TERRA": ,
    "TAYLOR": ,
    "TARMAC": ,
    "SWORKS": ,
    "SUR": ,
    "SUNB": ,
    "SUN": ,
    "SUBA /": ,
    "SUAB": ,
    "STRE": ,
    "STORM": ,
    "STEWART": ,
    "STE": ,
    "SPLZ": ,
    "SPLIZED": ,
    "SPECLIZD": ,
    "SMITH": ,
    "SIRRUS": ,
    "SION": ,
    "SHWIN": ,
    "SHENK": ,
    "SEABR": ,
    "SCWHINN": ,
    "SCOIN": ,
    "SCI": ,
    "SAFAR": ,
    "S WORKS": ,
    "RTS": ,
    "RR": ,
    "ROYAL": ,
    "ROBIN": ,
    "ROADT": ,
    "RNGRV": ,
    "RENEGADE": ,
    "RELIA": ,
    "RCKWD": ,
    "QUEST": ,
    "QIYE": ,
    "PTRB /": ,
    "PORSE": ,
    "PONTAIC": ,
    "PICK-UP": ,
    "PETB": ,
    "PACI": ,
    "PACEA": ,
    "OUTPOST": ,
    "OROAD": ,
    "OREGON": ,
    "ORCHARD": ,
    "OLDSM": ,
    "ODYSSEY": ,
    "NW HLND": ,
    "NORTHROC": ,
    "NFLYER": ,
    "NEWFLY": ,
    "NEW HOLLAND": ,
    "NAVIS": ,
    "NATSG": ,
    "NATIO": ,
    "NABO": ,
    "MVAU": ,
    "MOTOR": ,
    "MOTO GUZ": ,
    "MOTIVE": ,
    "MORGA": ,
    "MONTEREY": ,
    "MONSTER": ,
    "MONGOSE": ,
    "MONGOOS": ,
    "MOGU": ,
    "MISSAN": ,
    "MIDBS": ,
    "MICR": ,
    "MERZ/": ,
    "MECURY": ,
    "MBW": ,
    "MBNZ": ,
    "MAZDA /": ,
    "MASSEY": ,
    "MASA": ,
    "LINUS": ,
    "LINDY": ,
    "LIME CITY EQUPT": ,
    "LEZ": ,
    "LEXU /": ,
    "LEPRECHA": ,
    "LECTRIC": ,
    "LDAZE": ,
    "LANDROVER": ,
    "LANDINI": ,
    "LAJOLLA": ,
    "KRYSTAL": ,
    "KIO": ,
    "KENWRTH": ,
    "KAWAK": ,
    "KAW": ,
    "JUICED": ,
    "JOHNSTON": ,
    "JOHNSON": ,
    "JOHNDEER": ,
    "JAZZY": ,
    "IVEC": ,
    "ISUZA": ,
    "IPIPM": ,
    "INTST": ,
    "INTRNTNL": ,
    "INTERSTA": ,
    "INTERNL": ,
    "INIFNITI": ,
    "ICRPT": ,
    "IBIS": ,
    "HYUM": ,
    "HYNUDAI": ,
    "HUSQV": ,
    "HONF": ,
    "HOINDA": ,
    "HOBB": ,
    "HMC": ,
    "HITEC": ,
    "HIOND": ,
    "HD/": ,
    "HARL DAV": ,
    "HARL /": ,
    "GULF STR": ,
    "GRAVITY": ,
    "GLAVA": ,
    "GILLIC": ,
    "GHOST": ,
    "GEORGIE": ,
    "GENZE": ,
    "GENIE": ,
    "FUGI": ,
    "FS": ,
    "FRTLINER": ,
    "FRR": ,
    "FRHTLN": ,
    "FRHTL": ,
    "FRHGT": ,
    "FREU": ,
    "FREITLIN": ,
    "FREIHT": ,
    "FREIGT": ,
    "FORGE": ,
    "FORESTER": ,
    "FONA": ,
    "FLEETW": ,
    "FIXI": ,
    "FIAT-ABARTH": ,
    "FHT": ,
    "FGHT": ,
    "FABCO": ,
    "EASTON": ,
    "EASTERN": ,
    "E-Z-GO": ,
    "DUTCH": ,
    "DOGMA": ,
    "DODGE`": ,
    "DODGER": ,
    "DISCOVER": ,
    "DIPLOMAT": ,
    "DIAMONDBACK": ,
    "DEL SOL": ,
    "DEERE": ,
    "DCHR": ,
    "DAEWO": ,
    "CRY": ,
    "CRITICAL": ,
    "COOPER": ,
    "COACHMEN": ,
    "CLUBCAR": ,
    "CLARK": ,
    "CHVROLET": ,
    "CHRYL": ,
    "CHRI": ,
    "CHEVROET": ,
    "CHEVROEL": ,
    "CHEN": ,
    "CENTURY": ,
    "CCC": ,
    "CASE IH": ,
    "CARR": ,
    "CADA": ,
    "BSA": ,
    "BROWN": ,
    "BRENTWOO": ,
    "BREEZER": ,
    "BONTRAGE": ,
    "BOMBA": ,
    "BLIX": ,
    "BIGDOG": ,
    "BEST": ,
    "BEAVR": ,
    "BEAVE": ,
    "BAODIAO": ,
    "AUTO CAR": ,
    "APRIA": ,
    "AMEM": ,
    "ALL CITY": ,
    "ADUI": ,
    "ACUTA": ,
    "ACRU": ,
    "3G": ,
    "2016": ,
    "---": ,
    "--": ,
    "YOYT": ,
    "YETI": ,
    "YAHMA": ,
    "WTB": ,
    "WMARK": ,
    "WEISS": ,
    "WECO": ,
    "VOYAGER": ,
    "VORTEX": ,
    "VOLX": ,
    "VOLVA": ,
    "VOLOVO": ,
    "VOLOV": ,
    "VOLKWA": ,
    "VOLKSWAGON": ,
    "VOGU": ,
    "VLOKS": ,
    "VLKSWGN": ,
    "VLKSW": ,
    "VISIO": ,
    "VIPER": ,
    "VERSATIL": ,
    "V/W": ,
    "US": ,
    "UNION": ,
    "ULTEGRA": ,
    "TROPI": ,
    "TRLR": ,
    "TRKG": ,
    "TRI": ,
    "TREC": ,
    "TRAIN": ,
    "TR": ,
    "TOYOTRA": ,
    "TOYOTA`": ,
    "TOYOPET": ,
    "TOYOAT": ,
    "TOYO/": ,
    "TOYAT": ,
    "TOY/SCIO": ,
    "TOR": ,
    "TOMAS": ,
    "TIMBERLI": ,
    "THOMAS B": ,
    "THOC": ,
    "TESLA/": ,
    "TAO TAO": ,
    "TANK": ,
    "TAHOE": ,
    "TAHITI": ,
    "T0Y": ,
    "SWINN": ,
    "SWAGTRON": ,
    "SURVE": ,
    "SURGE": ,
    "SUPRE": ,
    "SUPER 73": ,
    "SUNSK": ,
    "SUBUARU": ,
    "SUBROSA": ,
    "SUBARY": ,
    "SUBARAU": ,
    "SUA": ,
    "STURN": ,
    "STRCRFT": ,
    "STOU": ,
    "STORCK": ,
    "STOLEN": ,
    "STINNER": ,
    "STCFT": ,
    "STAURN": ,
    "SRTUS": ,
    "SR": ,
    "SPRTN": ,
    "SPLZD": ,
    "SPECZD": ,
    "SPECILZD": ,
    "SPCLZED": ,
    "SPCIALZD": ,
    "SPAR": ,
    "SONDORS": ,
    "SOMA": ,
    "SOLARTEC": ,
    "SKYTRAK": ,
    "SKID": ,
    "SKATEBOA": ,
    "SILVER": ,
    "SIL": ,
    "SHAS": ,
    "SGHSK": ,
    "SE RACIN": ,
    "SE RACE": ,
    "SE BIKES": ,
    "SCOT": ,
    "SATY": ,
    "SARTO": ,
    "RUSSELL": ,
    "ROSS": ,
    "ROKETA": ,
    "ROAD MAS": ,
    "RIDGELAND": ,
    "RETRO": ,
    "RELI": ,
    "RED": ,
    "REALM": ,
    "RDMSTR": ,
    "RAVEN": ,
    "RANGE RV": ,
    "RAND": ,
    "RAMBLER": ,
    "RAMB": ,
    "RALLY": ,
    "RALLEY": ,
    "RALIEGH": ,
    "RADROVER": ,
    "R-VISION": ,
    "PTRD": ,
    "POCKET BIKE": ,
    "PLYMOTH": ,
    "PLYMO": ,
    "PJMFG": ,
    "PIERCE MFG": ,
    "PHANTOM": ,
    "PETKT": ,
    "PETERBUL": ,
    "PETERBL": ,
    "PETERBI": ,
    "PANT": ,
    "OTM": ,
    "ORC-RITE": ,
    "OLDSMO": ,
    "ODLS": ,
    "NWMR": ,
    "NISSNA": ,
    "NISSAS": ,
    "NISSAN /": ,
    "NISSA N": ,
    "NINEBOT": ,
    "NIISSAN": ,
    "NII": ,
    "NEXUS": ,
    "NEWMR": ,
    "NEOPLAN": ,
    "NEOPL": ,
    "NATL": ,
    "NAKTO": ,
    "MV AGUST": ,
    "MURRY": ,
    "MOUNT": ,
    "MOTORCYC": ,
    "MOTORCOA": ,
    "MOTOG": ,
    "MONARCH": ,
    "MONAC": ,
    "MOBIL": ,
    "MNI": ,
    "MITSH": ,
    "MITS.": ,
    "MITS /": ,
    "MINI BIK": ,
    "MGX": ,
    "METRO": ,
    "MERX": ,
    "MERK": ,
    "MERCEDS": ,
    "MERBENZ": ,
    "MERB/": ,
    "MCBZ": ,
    "MAZERATI": ,
    "MAZD /": ,
    "MAVERICK": ,
    "MASERATT": ,
    "MANTIS": ,
    "MANAC": ,
    "MADA": ,
    "MACDON": ,
    "MAC": ,
    "LUXUS": ,
    "LORAI": ,
    "LODAL": ,
    "LNDRVR": ,
    "LND": ,
    "LITESPED": ,
    "LINC /": ,
    "LIME-S": ,
    "LEZUS": ,
    "LEYLA": ,
    "LEXSS": ,
    "LEXAS": ,
    "LESU": ,
    "LEOPARD": ,
    "LANC": ,
    "LAMBO": ,
    "KVCH": ,
    "KOVATCH": ,
    "KOMFORT": ,
    "KNIGHT": ,
    "KM": ,
    "KINK": ,
    "KENW /": ,
    "KENT INT": ,
    "KENDA": ,
    "KANDI": ,
    "JLG LIFT": ,
    "JHNST": ,
    "JETTA": ,
    "JEPP": ,
    "JCB": ,
    "JAZZ": ,
    "J. DEERE": ,
    "ISZU": ,
    "ISUZI": ,
    "IRONH": ,
    "IRON HOR": ,
    "IRIZ": ,
    "INTWS": ,
    "INTS": ,
    "INTRN": ,
    "INTLNATL": ,
    "INTL /": ,
    "INT'L": ,
    "INDU": ,
    "IH": ,
    "ICOR": ,
    "ICCO": ,
    "ICBU": ,
    "HYUUN": ,
    "HYUU": ,
    "HYUNAI": ,
    "HYUIN": ,
    "HYU N": ,
    "HYOSU": ,
    "HURRICAN": ,
    "HR": ,
    "HONSA": ,
    "HONS": ,
    "HONG": ,
    "HONDAY": ,
    "HONDA MC": ,
    "HOMDA": ,
    "HOBBS": ,
    "HMMWV": ,
    "HIWAY": ,
    "HINO/": ,
    "HINDO": ,
    "HIN": ,
    "HENO": ,
    "HENDR": ,
    "HANDA": ,
    "H0NDA": ,
    "H D": ,
    "GULFSTRE": ,
    "GSXR": ,
    "GSCTR": ,
    "GRUMIN": ,
    "GRTDN": ,
    "GREAT DI": ,
    "GREAT": ,
    "GOSHE": ,
    "GOLD": ,
    "GO-PED": ,
    "GNC": ,
    "GMZ": ,
    "GMG": ,
    "GIORDANO": ,
    "GILLIG BUS": ,
    "GFSTR": ,
    "GENS": ,
    "GENERAL MOTORS CORP": ,
    "GENERAL": ,
    "GEM": ,
    "FTLR": ,
    "FSA": ,
    "FRIET": ,
    "FRHT /": ,
    "FRHK": ,
    "FRGTH": ,
    "FRANCO": ,
    "FORRD": ,
    "FORN": ,
    "FORESTRI": ,
    "FOREST": ,
    "FORDE": ,
    "FLYER": ,
    "FLTW": ,
    "FLETWOOD": ,
    "FLEETWOD": ,
    "FL": ,
    "FIXY": ,
    "FABRIQUE": ,
    "EZLDR": ,
    "EXPEDITI": ,
    "EXPED": ,
    "ENTEGRA": ,
    "ELUX": ,
    "ELITEBMX": ,
    "ELECTRIC BICYCLE": ,
    "ECOTRIC": ,
    "DYNACRAFT": ,
    "DUTCHMAN": ,
    "DUCTI": ,
    "DONG": ,
    "DOND": ,
    "DON": ,
    "DOGGE": ,
    "DODGW": ,
    "DODGE /": ,
    "DODG/": ,
    "DMNDBACK": ,
    "DMDBK": ,
    "DLPHN": ,
    "DK": ,
    "DISCO": ,
    "DIAMNDBK": ,
    "DHM": ,
    "DDOGE": ,
    "DDGE": ,
    "DATSU": ,
    "DAIXI": ,
    "DAHON": ,
    "D0DGE": ,
    "D-BACK": ,
    "CROSS": ,
    "CRONT": ,
    "CRAFTSMA": ,
    "COUNT": ,
    "COLT": ,
    "CLAAS": ,
    "CHYRSLER": ,
    "CHRYSLR": ,
    "CHRYS/": ,
    "CHRV": ,
    "CHRSY": ,
    "CHRIS": ,
    "CHINO": ,
    "CHEVEROL": ,
    "CHEVER": ,
    "CHER": ,
    "CHANG": ,
    "CERV": ,
    "CBR": ,
    "CATERPIL": ,
    "CASC": ,
    "CARRY": ,
    "CANOND": ,
    "CANDALE": ,
    "CADILA": ,
    "C HEV": ,
    "BROU": ,
    "BRCKT": ,
    "BRAVE": ,
    "BOX TRUC": ,
    "BOX": ,
    "BOREEM": ,
    "BOMBARDI": ,
    "BNW": ,
    "BNDR": ,
    "BMY": ,
    "BMW1": ,
    "BLUEBIR": ,
    "BLUE BIRD": ,
    "BLUBI": ,
    "BLAZING": ,
    "BLAZER": ,
    "BLADE Z": ,
    "BIG": ,
    "BICK": ,
    "BGTEX": ,
    "BEACHCRU": ,
    "BCC": ,
    "AZTEC": ,
    "AUSTI": ,
    "AUDU": ,
    "AUDI/": ,
    "AUDI /": ,
    "ARROW": ,
    "APOL": ,
    "APACH": ,
    "AMTRAK": ,
    "AMRCN": ,
    "AMGEN": ,
    "AMERL": ,
    "AMEB": ,
    "AM": ,
    "ALLEZ": ,
    "ALGRO": ,
    "ALCHEMY": ,
    "AIRBORNE": ,
    "AERBU": ,
    "ACUT": ,
    "ACUR /": ,
    "ACEE": ,
    "2015": ,
    "2014": ,
    "2001": ,
    "14TL": ,
    "ZYCLE": ,
    "ZOOM": ,
    "ZIEMN": ,
    "ZEPHYR": ,
    "ZEBRA": ,
    "YAMAMA": ,
    "XX": ,
    "XIAOMI": ,
    "X-TREME": ,
    "WSTRG": ,
    "WSTNS": ,
    "WRKHORSE": ,
    "WRIOR": ,
    "WORKS": ,
    "WOK": ,
    "WNESS": ,
    "WINNI": ,
    "WIND": ,
    "WILSO": ,
    "WILLIES": ,
    "WILDW": ,
    "WIEIER": ,
    "WHITEGMC": ,
    "WESTSTR": ,
    "WESTS": ,
    "WESTRN": ,
    "WESTR": ,
    "WESTMARK": ,
    "WESTERN STAR": ,
    "WESTAR": ,
    "WEST STR": ,
    "WELDCRAF": ,
    "WEILER": ,
    "WAUSAU": ,
    "WARRIOR": ,
    "WAN": ,
    "WALDON": ,
    "VOVO": ,
    "VOVLVO": ,
    "VOLVL": ,
    "VOLUME": ,
    "VOLSWAGE": ,
    "VOLLKS": ,
    "VOLKS`": ,
    "VOLKL": ,
    "VOLKD": ,
    "VN": ,
    "VLK": ,
    "VITUS": ,
    "VISTA": ,
    "VISON": ,
    "VIEW": ,
    "VIATHON": ,
    "VERMEER": ,
    "VERMAC": ,
    "VELOCITY": ,
    "VEEGO": ,
    "VECTOR": ,
    "VANPO": ,
    "VANG": ,
    "VAHN": ,
    "V & W": ,
    "USA": ,
    "UPTOWN": ,
    "UNVEGA": ,
    "UNNKNOWN": ,
    "UNIVE": ,
    "UNIT": ,
    "ULTRA": ,
    "UKNONWN": ,
    "UBER": ,
    "U-HAUL": ,
    "TURTL": ,
    "TUNDRA": ,
    "TRU": ,
    "TRTTE": ,
    "TRLT": ,
    "TRLKG": ,
    "TRK TRAC": ,
    "TRIUPH": ,
    "TRAVERSE": ,
    "TRAN": ,
    "TRAK": ,
    "TRAILRIT": ,
    "TRADE": ,
    "TRACKER": ,
    "TPY": ,
    "TOYO`": ,
    "TOYOTYA": ,
    "TOYOTR": ,
    "TOYOTAS": ,
    "TOYOCAR VAN": ,
    "TOYO/SCI": ,
    "TOY0TA": ,
    "TOY SCIO": ,
    "TOW TRUC": ,
    "TOW": ,
    "TOUT": ,
    "TOTYOA": ,
    "TOTOYTA": ,
    "TOTA": ,
    "TORO CO": ,
    "TICO": ,
    "TI": ,
    "THRUST": ,
    "THOR MOT": ,
    "THOMAS BUILT": ,
    "TEXTRON": ,
    "TESA": ,
    "TEMPEST": ,
    "TECUMSEH": ,
    "TAYLOR D": ,
    "TAOI": ,
    "TALLERIC": ,
    "TAKEUCHI": ,
    "TAKARA": ,
    "SYXMOTO": ,
    "SYMG": ,
    "SWING": ,
    "SWHLR": ,
    "SUZUKI/": ,
    "SUZU /": ,
    "SUZKI": ,
    "SUS": ,
    "SUPR": ,
    "SUNRA": ,
    "SUNNY D": ,
    "SUKI": ,
    "SUBRU": ,
    "SUBRARU": ,
    "SUBN": ,
    "SUBARI": ,
    "STWT&STV": ,
    "STRN /": ,
    "STRIC": ,
    "STRCF": ,
    "STORK": ,
    "STEVE RE": ,
    "STERLIN": ,
    "STERLI": ,
    "STEELMAN": ,
    "STARCR": ,
    "STAN": ,
    "SPZD": ,
    "SPRTR": ,
    "SPRITE": ,
    "SPRIN": ,
    "SPPR": ,
    "SPORTS": ,
    "SPORT": ,
    "SPOR": ,
    "SPMBL": ,
    "SPECIALE": ,
    "SPECIAL.": ,
    "SPECI": ,
    "SPEC.": ,
    "SPCON": ,
    "SPCIALIZ": ,
    "SPC": ,
    "SPALDING": ,
    "SOWIN": ,
    "SOLE": ,
    "SOLAR TE": ,
    "SOHOO": ,
    "SNTA CRZ": ,
    "SKY TRAK": ,
    "SKIDO": ,
    "SKAMPER": ,
    "SIMON": ,
    "SILVERLI": ,
    "SILV": ,
    "SHELBY": ,
    "SENATOR": ,
    "SEMI TRK": ,
    "SEAT": ,
    "SEAGRAVE FIRE APP": ,
    "SD70M": ,
    "SCU": ,
    "SCTION": ,
    "SCOTTY": ,
    "SCO": ,
    "SCIOIN": ,
    "SCIA": ,
    "SCHWYNN": ,
    "SCATANTE": ,
    "SCANI": ,
    "SAXON": ,
    "SAVA": ,
    "SATUN": ,
    "SAME": ,
    "SABZE": ,
    "SABU": ,
    "S-WORK": ,
    "RXHAL": ,
    "RVISION": ,
    "ROUBAIX": ,
    "ROTAX": ,
    "ROSSETTI": ,
    "ROROY": ,
    "RORD": ,
    "ROGUE": ,
    "ROD": ,
    "ROCKY": ,
    "ROAR": ,
    "ROADTEC": ,
    "RNGRVR": ,
    "RNG ROVR": ,
    "RITTE": ,
    "REYNOLDS": ,
    "REXHALL": ,
    "REXH": ,
    "REVCON": ,
    "RETROSPEC": ,
    "RED LINE": ,
    "REBOUND": ,
    "REACTION": ,
    "RDTRK": ,
    "RANS": ,
    "RANGER": ,
    "RANG": ,
    "RAN": ,
    "RAM 2500": ,
    "RALYE": ,
    "RALL": ,
    "RAGEN": ,
    "RADPOWER": ,
    "RAD POWE": ,
    "RAD CITY": ,
    "QUINN": ,
    "QUICK": ,
    "QR": ,
    "PURFIX": ,
    "PUMA": ,
    "PULSE": ,
    "PUCH": ,
    "PUBLIC": ,
    "PTRP": ,
    "PTRM": ,
    "PTRBUILT": ,
    "PTE": ,
    "PRT": ,
    "PRSUT": ,
    "PROWL": ,
    "PROVOST": ,
    "PROVI": ,
    "PROTERRA": ,
    "PROSCHE": ,
    "PROMASTE": ,
    "PROLINE": ,
    "POSTAL": ,
    "PORSCHE/": ,
    "PORSCE": ,
    "PONTIC": ,
    "PONIT": ,
    "POND": ,
    "POINT": ,
    "PLYMOU": ,
    "PLY": ,
    "PLEASURE": ,
    "PLEAS": ,
    "PLEA": ,
    "PJTRL": ,
    "PIAGGO": ,
    "PHOEN": ,
    "PHATCYCL": ,
    "PHAT CYC": ,
    "PHAETON": ,
    "PEUGOT": ,
    "PETT": ,
    "PETEBILT": ,
    "PENNY": ,
    "PEIRCE": ,
    "PARRO": ,
    "PANTHER": ,
    "PANEL": ,
    "PALOMAR": ,
    "PACCAR": ,
    "OYMA": ,
    "OXBO": ,
    "OTME": ,
    "OTAX": ,
    "ORTH": ,
    "OREGO": ,
    "OPUS": ,
    "OPEN ROAD": ,
    "ONYX": ,
    "ONEX": ,
    "ONDA": ,
    "OLS": ,
    "NYUN": ,
    "NWLFR": ,
    "NWFRL": ,
    "NW HOLLA": ,
    "NW HOLL": ,
    "NVRS": ,
    "NUWAY": ,
    "NTLRV": ,
    "NRCAL": ,
    "NOVA": ,
    "NORTHROCK": ,
    "NIZZ": ,
    "NIX": ,
    "NISSASN": ,
    "NISSANA": ,
    "NISSAM": ,
    "NISAS": ,
    "NISAA": ,
    "NIRVE": ,
    "NINER": ,
    "NHOLLAND": ,
    "NFOAI": ,
    "NF": ,
    "NEWM": ,
    "NEWHOLND": ,
    "NEWHOL": ,
    "NEWELL": ,
    "NEW HOLA": ,
    "NEW HOL": ,
    "NEW FLYER INDUSTRIES": ,
    "NAZDA": ,
    "NAVIO": ,
    "NATNL": ,
    "NAT SIG": ,
}
