from enum import Enum, unique


@unique
class Make(Enum):
    ACADIAN                 = "Acadian"
    ACURA                   = "Acura"
    ALFA_ROMERO             = "Alfa Romera"
    AMC                     = "American Motors"
    AMERICAN_LAFRANCE       = "American LaFrance"
    AUDI                    = "Audi"
    AUTOCAR                 = "Autocar"
    BENTLEY                 = "Bentley"
    BLUEBIRD                = "Bluebird"
    BMW                     = "BMW"
    BUICK                   = "Buick"
    CADILLAC                = "Cadillac"
    CHEVROLET               = "Chevrolet"
    CHRYSLER                = "ChrysleR"
    CROWN                   = "Crown"
    DAEWOO                  = "Daewoo"
    DATSUN                  = "Datsun"
    DELOREAN                = "Delorean"
    DODGE                   = "Dodge"
    DUCATI                  = "Ducati"
    FERRARI                 = "Ferrari"
    FIAT                    = "Fiat"
    FORD                    = "Ford"
    FREIGHTLINER            = "Freightliner"
    GEO                     = "Geo"
    GILLIG                  = "Gillig"
    GMC                     = "GMC"
    GRUMMAN                 = "Grumman"
    HARLEY                  = "Harley-Davidson"
    HINO                    = "Hino"
    HONDA                   = "Honda"
    HUMMER                  = "Hummer"
    HYUNDAI                 = "Hyundai"
    INFINITI                = "Infiniti"
    INTERNATIONAL_HARVESTER = "International Harvester"
    ISUZU                   = "Isuzu"
    JAGUAR                  = "Jaguar"
    JEEP                    = "Jeep"
    JOHN_DEERE              = "John Deere"
    KAWASAKI                = "Kawasaki"
    KENWORTH                = "Kenworth"
    KIA                     = "Kia"
    LAND_ROVER              = "Land Rover"
    LEXUS                   = "Lexus"
    LINCOLN                 = "Lincoln"
    MACK                    = "Mack"
    MASERATI                = "Maserati"
    MAZDA                   = "Mazda"
    MERCEDES_BENZ           = "Mercedes-Benz"
    MERCURY                 = "Mercury"
    MINI                    = "Mini"
    MITSUBISHI              = "Mitsubishi"
    NISSAN                  = "Nissan"
    NONE                    = None
    OLDSMOBILE              = "Oldsmobile"
    PETERBILT               = "Peterbilt"
    PETERBILT               = "Peterbilt"
    PLYMOUTH                = "Plymouth"
    PONTIAC                 = "Pontiac"
    PORSCHE                 = "Porsche"
    RADPOWER                = "Rad Power Bikes"
    RAM                     = "Ram"
    SAAB                    = "Saab"
    SATURN                  = "Saturn"
    SCHWINN                 = "Schwinn"
    SCION                   = "Scion"
    SMART                   = "Smart"
    STERLING                = "Sterling"
    SUBARU                  = "Subaru"
    SUZUKI                  = "Suzuki"
    TESLA                   = "Tesla"
    THOMAS                  = "Thomas"
    TOYOTA                  = "Toyota"
    TREK                    = "Trek"
    TRIUMPH                 = "Triumph"
    VESPA                   = "Vespa"
    VOLKSWAGEN              = "Volkswagen"
    VOLVO                   = "Volvo"
    WHITE                   = "White"
    WINNEBAGO               = "Winnebago"
    YAMAHA                  = "Yamaha"


MAKE_MAP = {
    "(UNK)": Make.NONE,
    "--": Make.NONE,
    "---": Make.NONE,
    "/": Make.NONE,
    "ACAD": Make.ACADIAN,
    "ACADIAN": Make.ACADIAN,
    "ACCURA": Make.ACURA,
    "ACRU": Make.ACURA,
    "ACRUA": Make.ACURA,
    "ACU": Make.ACURA,
    "ACUA": Make.ACURA,
    "ACUR /": Make.ACURA,
    "ACUR": Make.ACURA,
    "ACURA": Make.ACURA,
    "ACURA/": Make.ACURA,
    "ALFA ROMEO": Make.ALFA_ROMERO,
    "ALFA ROMERO": Make.ALFA_ROMERO,
    "ALFA": Make.ALFA_ROMERO,
    "ALFR": Make.ALFA_ROMERO,
    "AMER": Make.AMC,
    "AMERI": Make.AMC,
    "AMERICAN LA FRANCE": Make.AMERICAN_LAFRANCE,
    "AMERICAN MOTORS (AMC)": Make.AMC,
    "AMERICAN MOTORS": Make.AMC,
    "AMERICAN": Make.AMC,
    "AUD": Make.AUDI,
    "AUDI /": Make.AUDI,
    "AUDI": Make.AUDI,
    "AUDI/": Make.AUDI,
    "AUDU": Make.AUDI,
    "AUID": Make.AUDI,
    "AUIDI": Make.AUDI,
    "AUTOCAR": Make.AUTOCAR,
    "BENT": Make.BENTLEY,
    "BENTL": Make.BENTLEY,
    "BENTLEY": Make.BENTLEY,
    "BENZ": Make.MERCEDES_BENZ,
    "BLU BIRD": Make.BLUEBIRD,
    "BLU": Make.BLUEBIRD,
    "BLUB": Make.BLUEBIRD,
    "BLUBD": Make.BLUEBIRD,
    "BLUBI": Make.BLUEBIRD,
    "BLUBIRD": Make.BLUEBIRD,
    "BLUBR": Make.BLUEBIRD,
    "BLUBRD": Make.BLUEBIRD,
    "BLUE BIR": Make.BLUEBIRD,
    "BLUE BIRD": Make.BLUEBIRD,
    "BLUE": Make.BLUEBIRD,
    "BLUEB": Make.BLUEBIRD,
    "BLUEBIR": Make.BLUEBIRD,
    "BLUEBIRD (BUS)": Make.BLUEBIRD,
    "BLUEBIRD": Make.BLUEBIRD,
    "BMW /": Make.BMW,
    "BMW": Make.BMW,
    "BMW/": Make.BMW,
    "BMW1": Make.BMW,
    "BMW`": Make.BMW,
    "BUCIK": Make.BUICK,
    "BUCK": Make.BUICK,
    "BUI": Make.BUICK,
    "BUIC": Make.BUICK,
    "BUICK": Make.BUICK,
    "BUICK/": Make.BUICK,
    "BUIK": Make.BUICK,
    "BWM": Make.BMW,
    "BWW": Make.BMW,
    "CADI": Make.CADILLAC,
    "CADI/": Make.CADILLAC,
    "CADIL": Make.CADILLAC,
    "CADILA": Make.CADILLAC,
    "CADILAC": Make.CADILLAC,
    "CADILL": Make.CADILLAC,
    "CADILLA": Make.CADILLAC,
    "CADILLAC": Make.CADILLAC,
    "CEHV": Make.CHEVROLET,
    "CEHVY": Make.CHEVROLET,
    "CHEROLET": Make.CHEVROLET,
    "CHEV /": Make.CHEVROLET,
    "CHEV": Make.CHEVROLET,
    "CHEV/": Make.CHEVROLET,
    "CHEVE": Make.CHEVROLET,
    "CHEVER": Make.CHEVROLET,
    "CHEVEROL": Make.CHEVROLET,
    "CHEVEY": Make.CHEVROLET,
    "CHEVOLET": Make.CHEVROLET,
    "CHEVR": Make.CHEVROLET,
    "CHEVRLET": Make.CHEVROLET,
    "CHEVRLT": Make.CHEVROLET,
    "CHEVRO": Make.CHEVROLET,
    "CHEVROEL": Make.CHEVROLET,
    "CHEVROET": Make.CHEVROLET,
    "CHEVROL": Make.CHEVROLET,
    "CHEVROLE": Make.CHEVROLET,
    "CHEVROLET": Make.CHEVROLET,
    "CHEVROLT": Make.CHEVROLET,
    "CHEVT": Make.CHEVROLET,
    "CHEVY": Make.CHEVROLET,
    "CHEVY/": Make.CHEVROLET,
    "CHEV`": Make.CHEVROLET,
    "CHRS": Make.CHRYSLER,
    "CHRSLER": Make.CHRYSLER,
    "CHRSY": Make.CHRYSLER,
    "CHRY": Make.CHEVROLET,
    "CHRY/": Make.CHRYSLER,
    "CHRYL": Make.CHRYSLER,
    "CHRYLER": Make.CHRYSLER,
    "CHRYLSER": Make.CHRYSLER,
    "CHRYS": Make.CHRYSLER,
    "CHRYS/": Make.CHRYSLER,
    "CHRYSER": Make.CHRYSLER,
    "CHRYSL": Make.CHRYSLER,
    "CHRYSLE": Make.CHRYSLER,
    "CHRYSLER": Make.CHRYSLER,
    "CHRYSLR": Make.CHRYSLER,
    "CHRYST": Make.CHRYSLER,
    "CHRYSTLE": Make.CHRYSLER,
    "CHV": Make.CHEVROLET,
    "CHVROLET": Make.CHEVROLET,
    "CHVY": Make.CHEVROLET,
    "CHY": Make.CHRYSLER,
    "CHYRSLER": Make.CHRYSLER,
    "CHYSLER": Make.CHRYSLER,
    "CROW": Make.CROWN,
    "CROWN (BUS)": Make.CROWN,
    "CROWN": Make.CROWN,
    "CRY": Make.CHRYSLER,
    "CRYS": Make.CHRYSLER,
    "CRYSLER": Make.CHRYSLER,
    "D0DGE": Make.DODGE,
    "DAEW": Make.DAEWOO,
    "DAEWO": Make.DAEWOO,
    "DAEWOO": Make.DAEWOO,
    "DATS": Make.DATSUN,
    "DATSU": Make.DATSUN,
    "DATSUN": Make.DATSUN,
    "DATSUN/NISSAN": Make.NISSAN,
    "DDGE": Make.DODGE,
    "DDOGE": Make.DODGE,
    "DELOREAN": Make.DELOREAN,
    "DOD": Make.DODGE,
    "DODDGE": Make.DODGE,
    "DODE": Make.DODGE,
    "DODEG": Make.DODGE,
    "DODG /": Make.DODGE,
    "DODG": Make.DODGE,
    "DODG/": Make.DODGE,
    "DODGE /": Make.DODGE,
    "DODGE": Make.DODGE,
    "DODGE/": Make.DODGE,
    "DODGER": Make.DODGE,
    "DODGE`": Make.DODGE,
    "DODGW": Make.DODGE,
    "DOG": Make.DODGE,
    "DOGDE": Make.DODGE,
    "DOGE": Make.DODGE,
    "DOGGE": Make.DODGE,
    "DUCA": Make.DUCATI,
    "DUCAT": Make.DUCATI,
    "DUCATI (MOTORCYCLE)": Make.DUCATI,
    "DUCATI": Make.DUCATI,
    "DUCTI": Make.DUCATI,
    "FERRARA": Make.FERRARI,
    "FERRARI": Make.FERRARI,
    "FIAT": Make.FIAT,
    "FIAT-ABARTH": Make.FIAT,
    "FOR": Make.FORD,
    "FORC": Make.FORD,
    "FORD /": Make.FORD,
    "FORD": Make.FORD,
    "FORD/": Make.FORD,
    "FORDE": Make.FORD,
    "FORD`": Make.FORD,
    "FORE": Make.FORD,
    "FORED": Make.FORD,
    "FORF": Make.FORD,
    "FORN": Make.NONE,
    "FORR": Make.FORD,
    "FORRD": Make.FORD,
    "FORS": Make.FORD,
    "FRD": Make.FORD,
    "FREHT": Make.FREIGHTLINER,
    "FREI /": Make.FREIGHTLINER,
    "FREI": Make.FREIGHTLINER,
    "FREIG": Make.FREIGHTLINER,
    "FREIGH": Make.FREIGHTLINER,
    "FREIGHT LINER": Make.FREIGHTLINER,
    "FREIGHT": Make.FREIGHTLINER,
    "FREIGHTL": Make.FREIGHTLINER,
    "FREIGHTLINER CORP": Make.FREIGHTLINER,
    "FREIGHTLINER": Make.FREIGHTLINER,
    "FREIGT": Make.FREIGHTLINER,
    "FREIHT": Make.FREIGHTLINER,
    "FREIT": Make.FREIGHTLINER,
    "FREITLIN": Make.FREIGHTLINER,
    "FREITLNR": Make.FREIGHTLINER,
    "FRGH": Make.FREIGHTLINER,
    "FRGHT": Make.FREIGHTLINER,
    "FRGHT.": Make.FREIGHTLINER,
    "FRGHTLNR": Make.FREIGHTLINER,
    "FRGT": Make.FREIGHTLINER,
    "FRGTH": Make.FREIGHTLINER,
    "FRGTLNR": Make.FREIGHTLINER,
    "FRH": Make.FREIGHTLINER,
    "FRHGT": Make.FREIGHTLINER,
    "FRHI": Make.FREIGHTLINER,
    "FRHK": Make.FREIGHTLINER,
    "FRHT /": Make.FREIGHTLINER,
    "FRHT": Make.FREIGHTLINER,
    "FRHT.": Make.FREIGHTLINER,
    "FRHT/": Make.FREIGHTLINER,
    "FRHTL": Make.FREIGHTLINER,
    "FRHTLINE": Make.FREIGHTLINER,
    "FRHTLINR": Make.FREIGHTLINER,
    "FRHTLN": Make.FREIGHTLINER,
    "FRHTLNR": Make.FREIGHTLINER,
    "FRI": Make.FREIGHTLINER,
    "FRIE": Make.FREIGHTLINER,
    "FRIEGH": Make.FREIGHTLINER,
    "FRIEGHT": Make.FREIGHTLINER,
    "FRIEGHTL": Make.FREIGHTLINER,
    "FRIET": Make.FREIGHTLINER,
    "FRIGH": Make.FREIGHTLINER,
    "FRIGHT": Make.FREIGHTLINER,
    "FROD": Make.FORD,
    "FRT": Make.FREIGHTLINER,
    "FRTH": Make.FREIGHTLINER,
    "FRTL": Make.FREIGHTLINER,
    "FRTLINER": Make.FREIGHTLINER,
    "FRTLN": Make.FREIGHTLINER,
    "FRTLNR": Make.FREIGHTLINER,
    "FTL": Make.FREIGHTLINER,
    "FTLR": Make.FREIGHTLINER,
    "GENERAL MOTORS CORP": Make.GMC,
    "GENERAL": Make.GMC,
    "GEO": Make.GEO,
    "GILG": Make.GILLIG,
    "GILIG": Make.GILLIG,
    "GILL": Make.GILLIG,
    "GILLI": Make.GILLIG,
    "GILLIC": Make.GILLIG,
    "GILLIG (BUS)": Make.GILLIG,
    "GILLIG BUS": Make.GILLIG,
    "GILLIG": Make.GILLIG,
    "GM": Make.GMC,
    "GMA": Make.GMC,
    "GMC (GENERAL MOTORS)": Make.GMC,
    "GMC /": Make.GMC,
    "GMC": Make.GMC,
    "GMC/": Make.GMC,
    "GMG": Make.GMC,
    "GMS": Make.GMC,
    "GMV": Make.GMC,
    "GMX": Make.GMC,
    "GMZ": Make.GMC,
    "GNC": Make.GMC,
    "GRUM": Make.GRUMMAN,
    "GRUMAN": Make.GRUMMAN,
    "GRUMANN": Make.GRUMMAN,
    "GRUMIN": Make.GRUMMAN,
    "GRUMM": Make.GRUMMAN,
    "GRUMMAN MOTOR HOME": Make.GRUMMAN,
    "GRUMMAN": Make.GRUMMAN,
    "H0NDA": Make.HONDA,
    "HANDA": Make.HONDA,
    "HARL /": Make.HARLEY,
    "HARL DAV": Make.HARLEY,
    "HARL": Make.HARLEY,
    "HARLE": Make.HARLEY,
    "HARLEY D": Make.HARLEY,
    "HARLEY DAVIDSON": Make.HARLEY,
    "HARLEY": Make.HARLEY,
    "HARLEY-D": Make.HARLEY,
    "HARLEY-DAVIDSON": Make.HARLEY,
    "HARLEYD": Make.HARLEY,
    "HARLY": Make.HARLEY,
    "HD": Make.HARLEY,
    "HD/": Make.HARLEY,
    "HINO": Make.HINO,
    "HINO/": Make.HINO,
    "HIOND": Make.HONDA,
    "HIONDA": Make.HONDA,
    "HODNA": Make.HONDA,
    "HOINDA": Make.HONDA,
    "HON": Make.HONDA,
    "HONA": Make.HONDA,
    "HONAD": Make.HONDA,
    "HOND /": Make.HONDA,
    "HOND": Make.HONDA,
    "HOND/": Make.HONDA,
    "HONDA /": Make.HONDA,
    "HONDA MC": Make.HONDA,
    "HONDA": Make.HONDA,
    "HONDA/": Make.HONDA,
    "HONDAS": Make.HONDA,
    "HONDAY": Make.HONDA,
    "HONDA`": Make.HONDA,
    "HONDS": Make.HONDA,
    "HONE": Make.HONDA,
    "HONF": Make.HONDA,
    "HONG": Make.HONDA,
    "HONS": Make.HONDA,
    "HONSA": Make.HONDA,
    "HUMM": Make.HUMMER,
    "HUMME": Make.HUMMER,
    "HUMMER": Make.HUMMER,
    "HUMVEE": Make.HUMMER,
    "HUN": Make.HYUNDAI,
    "HUNDAI": Make.HYUNDAI,
    "HUYN": Make.HYUNDAI,
    "HUYNDAI": Make.HYUNDAI,
    "HYN": Make.HYUNDAI,
    "HYND": Make.HYUNDAI,
    "HYNDAI": Make.HYUNDAI,
    "HYNU": Make.HYUNDAI,
    "HYNUDAI": Make.HYUNDAI,
    "HYU N": Make.HYUNDAI,
    "HYU": Make.HYUNDAI,
    "HYUAN": Make.HYUNDAI,
    "HYUANDAI": Make.HYUNDAI,
    "HYUD": Make.HYUNDAI,
    "HYUDAI": Make.HYUNDAI,
    "HYUIN": Make.HYUNDAI,
    "HYUM": Make.HYUNDAI,
    "HYUN /": Make.HYUNDAI,
    "HYUN": Make.HYUNDAI,
    "HYUN/": Make.HYUNDAI,
    "HYUNA": Make.HYUNDAI,
    "HYUNAI": Make.HYUNDAI,
    "HYUND": Make.HYUNDAI,
    "HYUNDA": Make.HYUNDAI,
    "HYUNDAI": Make.HYUNDAI,
    "HYUNDAI/": Make.HYUNDAI,
    "HYUNDAU": Make.HYUNDAI,
    "HYUNDAY": Make.HYUNDAI,
    "HYUNDI": Make.HYUNDAI,
    "HYUNDIA": Make.HYUNDAI,
    "HYUU": Make.HYUNDAI,
    "HYUUN": Make.HYUNDAI,
    "INF": Make.INFINITI,
    "INFI /": Make.INFINITI,
    "INFI": Make.INFINITI,
    "INFIN": Make.INFINITI,
    "INFIN/": Make.INFINITI,
    "INFINI": Make.INFINITI,
    "INFINIT": Make.INFINITI,
    "INFINITE": Make.INFINITI,
    "INFINITI": Make.INFINITI,
    "INFINITY": Make.INFINITI,
    "INFINT": Make.INFINITI,
    "INFINTI": Make.INFINITI,
    "INFINTY": Make.INFINITI,
    "INFIT": Make.INFINITI,
    "INIF": Make.INFINITI,
    "INIFI": Make.INFINITI,
    "INIFINIT": Make.INFINITI,
    "INIFNITI": Make.INFINITI,
    "INTER": Make.INTERNATIONAL_HARVESTER,
    "INTERNAT": Make.INTERNATIONAL_HARVESTER,
    "INTERNATIONAL HARVESTER": Make.INTERNATIONAL_HARVESTER,
    "INTL": Make.NONE,
    "ISU": Make.ISUZU,
    "ISUZ": Make.ISUZU,
    "ISUZU": Make.ISUZU,
    "JAG": Make.JAGUAR,
    "JAGA": Make.JAGUAR,
    "JAGU": Make.JAGUAR,
    "JAGUA": Make.JAGUAR,
    "JAGUAR": Make.JAGUAR,
    "JDEER": Make.JOHN_DEERE,
    "JEE": Make.JEEP,
    "JEEEP": Make.JEEP,
    "JEEF": Make.JEEP,
    "JEEO": Make.JEEP,
    "JEEP /": Make.JEEP,
    "JEEP": Make.JEEP,
    "JEEP/": Make.JEEP,
    "JEPP": Make.JEEP,
    "JOHN DEE": Make.JOHN_DEERE,
    "JOHN DEER": Make.JOHN_DEERE,
    "JOHN DEERE": Make.JOHN_DEERE,
    "JOHN": Make.JOHN_DEERE,
    "JOHND": Make.JOHN_DEERE,
    "JOHNDEER": Make.JOHN_DEERE,
    "KAWA": Make.KAWASAKI,
    "KAWAI": Make.KAWASAKI,
    "KAWAK": Make.KAWASAKI,
    "KAWAS": Make.KAWASAKI,
    "KAWASA": Make.KAWASAKI,
    "KAWASAK": Make.KAWASAKI,
    "KAWASAKI": Make.KAWASAKI,
    "KAWASKI": Make.KAWASAKI,
    "KAWI": Make.KAWASAKI,
    "KAWK": Make.KAWASAKI,
    "KENW": Make.KENWORTH,
    "KENWO": Make.KENWORTH,
    "KENWOR": Make.KENWORTH,
    "KENWORT": Make.KENWORTH,
    "KENWORTH": Make.KENWORTH,
    "KENWRTH": Make.KENWORTH,
    "KIA /": Make.KIA,
    "KIA": Make.KIA,
    "KIA/": Make.KIA,
    "KIO": Make.KIA,
    "KIS": Make.KIA,
    "LAND ROVER": Make.LAND_ROVER,
    "LAND RVR": Make.LAND_ROVER,
    "LAND": Make.LAND_ROVER,
    "LANDR": Make.LAND_ROVER,
    "LANDRO": Make.LAND_ROVER,
    "LANDROVE": Make.LAND_ROVER,
    "LANDROVER": Make.LAND_ROVER,
    "LANDRVR": Make.LAND_ROVER,
    "LES": Make.LEXUS,
    "LESU": Make.LEXUS,
    "LEX": Make.LEXUS,
    "LEXAS": Make.LEXUS,
    "LEXI": Make.LEXUS,
    "LEXIS": Make.LEXUS,
    "LEXS /": Make.LEXUS,
    "LEXS": Make.LEXUS,
    "LEXSS": Make.LEXUS,
    "LEXSUS": Make.LEXUS,
    "LEXU /": Make.LEXUS,
    "LEXU": Make.LEXUS,
    "LEXUS": Make.LEXUS,
    "LEXUS/": Make.LEXUS,
    "LEXUX": Make.LEXUS,
    "LEZ": Make.LEXUS,
    "LEZUS": Make.LEXUS,
    "LICOLN": Make.LINCOLN,
    "LIN": Make.LINCOLN,
    "LINC /": Make.LINCOLN,
    "LINC": Make.LINCOLN,
    "LINCL": Make.LINCOLN,
    "LINCO": Make.LINCOLN,
    "LINCOL": Make.LINCOLN,
    "LINCOLN CONTINENTAL": Make.LINCOLN,
    "LINCOLN": Make.LINCOLN,
    "LINCOLN/": Make.LINCOLN,
    "LINCON": Make.LINCOLN,
    "LND RVR": Make.LAND_ROVER,
    "LNDR": Make.LAND_ROVER,
    "LNDRVR": Make.LAND_ROVER,
    "LUXUS": Make.LEXUS,
    "LXS": Make.LEXUS,
    "MACK": Make.MACK,
    "MADA": Make.MAZDA,
    "MADZA": Make.MAZDA,
    "MASE": Make.MASERATI,
    "MASER": Make.MASERATI,
    "MASERATI": Make.MASERATI,
    "MASERATT": Make.MASERATI,
    "MASI": Make.MASERATI,
    "MAXDA": Make.MAZDA,
    "MAZ": Make.MAZDA,
    "MAZA": Make.MAZDA,
    "MAZAD": Make.MAZDA,
    "MAZADA": Make.MAZDA,
    "MAZD /": Make.MAZDA,
    "MAZD": Make.MAZDA,
    "MAZDA /": Make.MAZDA,
    "MAZDA 3": Make.MAZDA,
    "MAZDA 6": Make.MAZDA,
    "MAZDA": Make.MAZDA,
    "MAZDA/": Make.MAZDA,
    "MAZDZ": Make.MAZDA,
    "MAZERATI": Make.MASERATI,
    "MERB /": Make.MERCEDES_BENZ,
    "MERB": Make.MERCEDES_BENZ,
    "MERB.": Make.MERCEDES_BENZ,
    "MERB/": Make.MERCEDES_BENZ,
    "MERBENZ": Make.MERCEDES_BENZ,
    "MERBNZ": Make.MERCEDES_BENZ,
    "MERC": Make.MERCURY,
    "MERCE": Make.MERCEDES_BENZ,
    "MERCED": Make.MERCEDES_BENZ,
    "MERCEDE": Make.MERCEDES_BENZ,
    "MERCEDES BENZ": Make.MERCEDES_BENZ,
    "MERCEDES": Make.MERCEDES_BENZ,
    "MERCEDES-BENZ": Make.MERCEDES_BENZ,
    "MERCEDEZ": Make.MERCEDES_BENZ,
    "MERCEDS": Make.MERCEDES_BENZ,
    "MERCU": Make.MERCURY,
    "MERCUR": Make.MERCURY,
    "MERCURY": Make.MERCURY,
    "MERD": Make.MERCURY,
    "MERZ /": Make.MERCEDES_BENZ,
    "MERZ BNZ": Make.MERCEDES_BENZ,
    "MERZ": Make.MERCEDES_BENZ,
    "MERZ/": Make.MERCEDES_BENZ,
    "MERZB": Make.MERCEDES_BENZ,
    "MINI COOPER": Make.MINI,
    "MINI": Make.MINI,
    "MINN": Make.MINI,
    "MINNI": Make.MINI,
    "MISCELLANEOUS": Make.NONE,
    "MISSAN": Make.NISSAN,
    "MIST": Make.MITSUBISHI,
    "MISTU": Make.MITSUBISHI,
    "MIT": Make.MITSUBISHI,
    "MITI": Make.MITSUBISHI,
    "MITS /": Make.MITSUBISHI,
    "MITS": Make.MITSUBISHI,
    "MITS.": Make.MITSUBISHI,
    "MITS/": Make.MITSUBISHI,
    "MITSH": Make.MITSUBISHI,
    "MITSU": Make.MITSUBISHI,
    "MITSUB": Make.MITSUBISHI,
    "MITSUBI": Make.MITSUBISHI,
    "MITSUBIS": Make.MITSUBISHI,
    "MITSUBISHI": Make.MITSUBISHI,
    "MITT": Make.MITSUBISHI,
    "MITTS": Make.MITSUBISHI,
    "MITU": Make.MITSUBISHI,
    "MITZ": Make.MITSUBISHI,
    "MNI": Make.MINI,
    "MNICP": Make.MINI,
    "MNNI": Make.MINI,
    "MZD": Make.MAZDA,
    "MZDA": Make.MAZDA,
    "N/A": Make.NONE,
    "NII": Make.NISSAN,
    "NIIS": Make.NISSAN,
    "NIISAN": Make.NISSAN,
    "NIISS": Make.NISSAN,
    "NIISSAN": Make.NISSAN,
    "NIS": Make.NISSAN,
    "NISA": Make.NISSAN,
    "NISAA": Make.NISSAN,
    "NISAAN": Make.NISSAN,
    "NISAN": Make.NISSAN,
    "NISAS": Make.NISSAN,
    "NISS /": Make.NISSAN,
    "NISS": Make.NISSAN,
    "NISS/": Make.NISSAN,
    "NISSA N": Make.NISSAN,
    "NISSA": Make.NISSAN,
    "NISSAM": Make.NISSAN,
    "NISSAN /": Make.NISSAN,
    "NISSAN": Make.NISSAN,
    "NISSAN/": Make.NISSAN,
    "NISSANA": Make.NISSAN,
    "NISSAN`": Make.NISSAN,
    "NISSAS": Make.NISSAN,
    "NISSASN": Make.NISSAN,
    "NISSI": Make.NISSAN,
    "NISSIAN": Make.NISSAN,
    "NISSN": Make.NISSAN,
    "NISSNA": Make.NISSAN,
    "NISSS": Make.NISSAN,
    "NISSSAN": Make.NISSAN,
    "NOT STATED": Make.NONE,
    "ODYSSEY": Make.HONDA,
    "OLDS": Make.OLDSMOBILE,
    "OLDSM": Make.OLDSMOBILE,
    "OLDSMO": Make.OLDSMOBILE,
    "OLDSMOBI": Make.OLDSMOBILE,
    "OLDSMOBILE": Make.OLDSMOBILE,
    "OLS": Make.OLDSMOBILE,
    "OTHER - ATV": Make.NONE,
    "OTHER - AUTO": Make.NONE,
    "OTHER - BUS": Make.NONE,
    "OTHER - DOMESTIC": Make.NONE,
    "OTHER - MOPED": Make.NONE,
    "OTHER - MOTORCYCLE": Make.NONE,
    "OTHER - MOTORHOME": Make.NONE,
    "OTHER - PICKUP": Make.NONE,
    "OTHER - SCHOOL BUS": Make.NONE,
    "OTHER - TRUCK": Make.NONE,
    "OTHER DOMESTICS": Make.NONE,
    "OTHER FOREIGN": Make.NONE,
    "OTHER": Make.NONE,
    "PETE": Make.PETERBILT,
    "PETEBILT": Make.PETERBILT,
    "PETER": Make.PETERBILT,
    "PETERB": Make.PETERBILT,
    "PETERBI": Make.PETERBILT,
    "PETERBIL": Make.PETERBILT,
    "PETERBILT": Make.PETERBILT,
    "PETERBL": Make.PETERBILT,
    "PETERBLT": Make.PETERBILT,
    "PETERBU": Make.PETERBILT,
    "PETERBUI": Make.PETERBILT,
    "PETERBUILT": Make.PETERBILT,
    "PETERBUL": Make.PETERBILT,
    "PETKT": Make.PETERBILT,
    "PETR": Make.PETERBILT,
    "PETRB": Make.PETERBILT,
    "PETRBILT": Make.PETERBILT,
    "PETRBLT": Make.PETERBILT,
    "PLY": Make.PLYMOUTH,
    "PLYM": Make.PLYMOUTH,
    "PLYMO": Make.PLYMOUTH,
    "PLYMOTH": Make.PLYMOUTH,
    "PLYMOU": Make.PLYMOUTH,
    "PLYMOUTH": Make.PLYMOUTH,
    "PONI": Make.PONTIAC,
    "PONIT": Make.PONTIAC,
    "PONITAC": Make.PONTIAC,
    "PONT": Make.PONTIAC,
    "PONTAIC": Make.PONTIAC,
    "PONTI": Make.PONTIAC,
    "PONTIA": Make.PONTIAC,
    "PONTIAC": Make.PONTIAC,
    "PONTIAC/": Make.PONTIAC,
    "PONTIC": Make.PONTIAC,
    "POR": Make.PORSCHE,
    "PORC": Make.PORSCHE,
    "PORCH": Make.PORSCHE,
    "PORCHE": Make.PORSCHE,
    "PORS": Make.PORSCHE,
    "PORSC": Make.PORSCHE,
    "PORSCE": Make.PORSCHE,
    "PORSCH": Make.PORSCHE,
    "PORSCHE": Make.PORSCHE,
    "PORSCHE/": Make.PORSCHE,
    "PORSE": Make.PORSCHE,
    "PORSH": Make.PORSCHE,
    "PORSHE": Make.PORSCHE,
    "PRIUS": Make.TOYOTA,
    "PRTB": Make.PETERBILT,
    "PTB": Make.PETERBILT,
    "PTBL": Make.PETERBILT,
    "PTBLT": Make.PETERBILT,
    "PTBR": Make.PETERBILT,
    "PTBT": Make.PETERBILT,
    "PTE": Make.PETERBILT,
    "PTER": Make.PETERBILT,
    "PTR": Make.PETERBILT,
    "PTRB /": Make.PETERBILT,
    "PTRB": Make.PETERBILT,
    "PTRB/": Make.PETERBILT,
    "PTRBILT": Make.PETERBILT,
    "PTRBL": Make.PETERBILT,
    "PTRBLT": Make.PETERBILT,
    "PTRBT": Make.PETERBILT,
    "PTRBUILT": Make.PETERBILT,
    "RAD CITY": Make.RADPOWER,
    "RAD POWE": Make.RADPOWER,
    "RAD": Make.RADPOWER,
    "RADPOWER": Make.RADPOWER,
    "RADROVER": Make.RADPOWER,
    "RAM 2500": Make.RAM,
    "RAM": Make.RAM,
    "RAM/": Make.RAM,
    "RAN": Make.RAM,
    "RANG": Make.LAND_ROVER,
    "RANGE RO": Make.LAND_ROVER,
    "RANGE ROVER": Make.LAND_ROVER,
    "RANGE RV": Make.LAND_ROVER,
    "RANGE": Make.LAND_ROVER,
    "RANGER": Make.LAND_ROVER,
    "RANGEROV": Make.LAND_ROVER,
    "RNG ROVR": Make.LAND_ROVER,
    "RNG RVR": Make.LAND_ROVER,
    "RNGRV": Make.LAND_ROVER,
    "RNGRVR": Make.LAND_ROVER,
    "RORD": Make.FORD,
    "ROVER": Make.LAND_ROVER,
    "SAAB": Make.SAAB,
    "SATN": Make.SATURN,
    "SATR": Make.SATURN,
    "SATRN": Make.SATURN,
    "SATRU": Make.SATURN,
    "SATRUN": Make.SATURN,
    "SATU": Make.SATURN,
    "SATUN": Make.SATURN,
    "SATUR": Make.SATURN,
    "SATURN": Make.SATURN,
    "SATURN/": Make.SATURN,
    "SATY": Make.SATURN,
    "SCHW": Make.SCHWINN,
    "SCHWIN": Make.SCHWINN,
    "SCHWINN": Make.SCHWINN,
    "SCHWYNN": Make.SCHWINN,
    "SCIO": Make.SCION,
    "SCIOIN": Make.SCION,
    "SCION": Make.SCION,
    "SCOIN": Make.SCION,
    "SCWHINN": Make.SCHWINN,
    "SCWINN": Make.SCHWINN,
    "SHWIN": Make.SCHWINN,
    "SHWINN": Make.SCHWINN,
    "SMAR": Make.SMART,
    "SMART": Make.SMART,
    "STERLI": Make.STERLING,
    "STERLIN": Make.STERLING,
    "STERLING": Make.STERLING,
    "STRN /": Make.SATURN,
    "STRN": Make.SATURN,
    "STURN": Make.SATURN,
    "SUB": Make.SUBARU,
    "SUBA /": Make.SUBARU,
    "SUBA": Make.SUBARU,
    "SUBAR": Make.SUBARU,
    "SUBARA": Make.SUBARU,
    "SUBARAU": Make.SUBARU,
    "SUBARI": Make.SUBARU,
    "SUBARU": Make.SUBARU,
    "SUBARU/": Make.SUBARU,
    "SUBARY": Make.SUBARU,
    "SUBI": Make.SUBARU,
    "SUBN": Make.SUBARU,
    "SUBR": Make.SUBARU,
    "SUBRA": Make.SUBARU,
    "SUBRARU": Make.SUBARU,
    "SUBRAU": Make.SUBARU,
    "SUBRU": Make.SUBARU,
    "SUBU": Make.SUBARU,
    "SUBUARU": Make.SUBARU,
    "SUBUR": Make.SUBARU,
    "SUBURA": Make.SUBARU,
    "SUBURU": Make.SUBARU,
    "SUS": Make.SUZUKI,
    "SUSUKI": Make.SUZUKI,
    "SUV": Make.NONE,
    "SUZ": Make.SUZUKI,
    "SUZI": Make.SUZUKI,
    "SUZIKI": Make.SUZUKI,
    "SUZK": Make.SUZUKI,
    "SUZKI": Make.SUZUKI,
    "SUZU /": Make.SUZUKI,
    "SUZU": Make.SUZUKI,
    "SUZUK": Make.SUZUKI,
    "SUZUKI MC": Make.SUZUKI,
    "SUZUKI": Make.SUZUKI,
    "SUZUKI/": Make.SUZUKI,
    "T0Y": Make.TOYOTA,
    "T0YOTA": Make.TOYOTA,
    "TAHOE": Make.GMC,
    "TAOTA": Make.TOYOTA,
    "TAOTAO": Make.TOYOTA,
    "TESL": Make.TESLA,
    "TESLA MOTORS": Make.TESLA,
    "TESLA": Make.TESLA,
    "TESLA/": Make.TESLA,
    "THOM": Make.THOMAS,
    "THOMA": Make.THOMAS,
    "THOMAS (BUS)": Make.THOMAS,
    "THOMAS B": Make.THOMAS,
    "THOMAS": Make.THOMAS,
    "TOT": Make.TOYOTA,
    "TOTA": Make.TOYOTA,
    "TOTO": Make.TOYOTA,
    "TOTOTA": Make.TOYOTA,
    "TOTOYA": Make.TOYOTA,
    "TOTOYTA": Make.TOYOTA,
    "TOTY": Make.TOYOTA,
    "TOTYOA": Make.TOYOTA,
    "TOTYOTA": Make.TOYOTA,
    "TOY": Make.TOYOTA,
    "TOY/SCIO": Make.TOYOTA,
    "TOY0": Make.TOYOTA,
    "TOY0TA": Make.TOYOTA,
    "TOYA": Make.TOYOTA,
    "TOYAT": Make.TOYOTA,
    "TOYATA": Make.TOYOTA,
    "TOYI": Make.TOYOTA,
    "TOYO /": Make.TOYOTA,
    "TOYO": Make.TOYOTA,
    "TOYO/": Make.TOYOTA,
    "TOYO/SCI": Make.TOYOTA,
    "TOYOA": Make.TOYOTA,
    "TOYOAT": Make.TOYOTA,
    "TOYORA": Make.TOYOTA,
    "TOYOT": Make.TOYOTA,
    "TOYOTA": Make.TOYOTA,
    "TOYOTA/": Make.TOYOTA,
    "TOYOTAS": Make.TOYOTA,
    "TOYOTA`": Make.TOYOTA,
    "TOYOTO": Make.TOYOTA,
    "TOYOTOA": Make.TOYOTA,
    "TOYOTR": Make.TOYOTA,
    "TOYOTRA": Make.TOYOTA,
    "TOYOTS": Make.TOYOTA,
    "TOYOTYA": Make.TOYOTA,
    "TOYOY": Make.TOYOTA,
    "TOYOYA": Make.TOYOTA,
    "TOYOYTA": Make.TOYOTA,
    "TOYO`": Make.TOYOTA,
    "TOYR": Make.TOYOTA,
    "TOYT /": Make.TOYOTA,
    "TOYT": Make.TOYOTA,
    "TOYT.": Make.TOYOTA,
    "TOYT/": Make.TOYOTA,
    "TOYT/SCI": Make.TOYOTA,
    "TOYTA": Make.TOYOTA,
    "TOYTO": Make.TOYOTA,
    "TOYTOA": Make.TOYOTA,
    "TOYTOTA": Make.TOYOTA,
    "TOYTT": Make.TOYOTA,
    "TOYY": Make.TOYOTA,
    "TREC": Make.TREK,
    "TRECK": Make.TREK,
    "TREK": Make.TREK,
    "TREK, INC.": Make.TREK,
    "TRIPH": Make.TRIUMPH,
    "TRIU": Make.TRIUMPH,
    "TRIUM": Make.TRIUMPH,
    "TRIUMP": Make.TRIUMPH,
    "TRIUMPH": Make.TRIUMPH,
    "TRIUPH": Make.TRIUMPH,
    "TRUIMPH": Make.TRIUMPH,
    "TRUM": Make.TRIUMPH,
    "TSLA": Make.TESLA,
    "TSMR": Make.TESLA,
    "TUNDRA": Make.TOYOTA,
    "TYOT": Make.TOYOTA,
    "TYOTA": Make.TOYOTA,
    "UBER": Make.NONE,
    "UKN": Make.NONE,
    "UKNONWN": Make.NONE,
    "UKNOWN": Make.NONE,
    "UNK /": Make.NONE,
    "UNK": Make.NONE,
    "UNK.": Make.NONE,
    "UNK/": Make.NONE,
    "UNKN": Make.NONE,
    "UNKN/": Make.NONE,
    "UNKNONW": Make.NONE,
    "UNKNOW": Make.NONE,
    "UNKNOWN": Make.NONE,
    "UNKNOWN/": Make.NONE,
    "UNKNWN": Make.NONE,
    "UNKNWON": Make.NONE,
    "UNKOWN": Make.NONE,
    "UNKWN": Make.NONE,
    "UNNKNOWN": Make.NONE,
    "UNNOWN": Make.NONE,
    "V & W": Make.VOLKSWAGEN,
    "V W": Make.VOLKSWAGEN,
    "V.W.": Make.VOLKSWAGEN,
    "V/W": Make.VOLKSWAGEN,
    "VESP": Make.VESPA,
    "VESPA": Make.VESPA,
    "VOK": Make.VOLKSWAGEN,
    "VOKS": Make.VOLKSWAGEN,
    "VOLCO": Make.VOLVO,
    "VOLK /": Make.VOLKSWAGEN,
    "VOLK": Make.VOLKSWAGEN,
    "VOLK/": Make.VOLKSWAGEN,
    "VOLKD": Make.VOLKSWAGEN,
    "VOLKL": Make.VOLKSWAGEN,
    "VOLKS": Make.VOLKSWAGEN,
    "VOLKS/": Make.VOLKSWAGEN,
    "VOLKSW": Make.VOLKSWAGEN,
    "VOLKSWA": Make.VOLKSWAGEN,
    "VOLKSWAG": Make.VOLKSWAGEN,
    "VOLKSWAGEN": Make.VOLKSWAGEN,
    "VOLKSWAGON": Make.VOLKSWAGEN,
    "VOLKSWGN": Make.VOLKSWAGEN,
    "VOLKS`": Make.VOLKSWAGEN,
    "VOLKW": Make.VOLKSWAGEN,
    "VOLKWA": Make.VOLKSWAGEN,
    "VOLKWAGE": Make.VOLKSWAGEN,
    "VOLKWGN": Make.VOLKSWAGEN,
    "VOLLK": Make.VOLKSWAGEN,
    "VOLLKS": Make.VOLKSWAGEN,
    "VOLO": Make.VOLVO,
    "VOLOV": Make.VOLVO,
    "VOLOVO": Make.VOLVO,
    "VOLS": Make.VOLKSWAGEN,
    "VOLSWAGE": Make.VOLKSWAGEN,
    "VOLSWGN": Make.VOLKSWAGEN,
    "VOLV /": Make.VOLVO,
    "VOLV": Make.VOLVO,
    "VOLV0": Make.VOLVO,
    "VOLVA": Make.VOLVO,
    "VOLVE": Make.VOLVO,
    "VOLVL": Make.VOLVO,
    "VOLVO": Make.VOLVO,
    "VOLVO/": Make.VOLVO,
    "VOLW": Make.VOLKSWAGEN,
    "VOLX": Make.VOLKSWAGEN,
    "VOVL": Make.VOLVO,
    "VOVLO": Make.VOLVO,
    "VOVLVO": Make.VOLVO,
    "VOVO": Make.VOLVO,
    "VOYAGER": Make.PLYMOUTH,
    "VW": Make.VOLKSWAGEN,
    "WHITE GMC": Make.GMC,
    "WHITE VOLVO": Make.VOLVO,
    "WHITE": Make.WHITE,
    "WHITEGMC": Make.GMC,
    "WINN": Make.WINNEBAGO,
    "WINNE": Make.WINNEBAGO,
    "WINNEBAG": Make.WINNEBAGO,
    "WINNEBAGO": Make.WINNEBAGO,
    "WINNI": Make.WINNEBAGO,
    "WNBG": Make.WINNEBAGO,
    "WNBGO": Make.WINNEBAGO,
    "YAH": Make.YAMAHA,
    "YAHA": Make.YAMAHA,
    "YAHAMA": Make.YAMAHA,
    "YAHMA": Make.YAMAHA,
    "YAM": Make.YAMAHA,
    "YAMA": Make.YAMAHA,
    "YAMAH": Make.YAMAHA,
    "YAMAHA": Make.YAMAHA,
    "YAMAMA": Make.YAMAHA,
    "YAMH": Make.YAMAHA,
    "________": Make.NONE,
}
